changelog:
  categories:
    - title: Breaking Changes
      labels:
        - "breaking-change"
    - title: Table Changes
      labels:
        - "component:table"
    - title: Build and Package
      labels:
        - "component:build&packaging"
    - title: Features and Improvements
      labels:
        - "features-improvements"
    - title: Bug Fixes
      labels:
        - "bug-fixes"
    - title: General # Non-code changes like tests, CI, documentation
      labels:
        - "*"
