changelog:
  categories:
    - title: Breaking Changes
      labels:
        - "breaking-change"
    - title: Table Changes
      labels:
        - "component:table"
    - title: Features and Improvements
      labels:
        - "features-improvements"
    - title: Bug Fixes
      labels:
        - "bug-fixes"
    - title: Performance Improvements
      labels:
        - "performance"
    - title: Observability
      labels:
        - "observability"
    - title: Build and Package
      labels:
        - "component:build&packaging"
    - title: Tests, Docs, and Other No-op Changes
      labels:
        - "tests-docs"
    - title: Dependency Updates
      labels:
        - "dependencies"
    - title: General # Non-code changes like tests, CI, documentation
      labels:
        - "*"
