// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	tuf "github.com/kolide/updater/tuf"
	mock "github.com/stretchr/testify/mock"
)

// Updater is an autogenerated mock type for the updater type
type Updater struct {
	mock.Mock
}

// Run provides a mock function with given fields: opts
func (_m *Updater) Run(opts ...tuf.Option) (func(), error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 func()
	if rf, ok := ret.Get(0).(func(...tuf.Option) func()); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...tuf.Option) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
