// Code generated by mockery v2.21.1. DO NOT EDIT.

package tuf

import mock "github.com/stretchr/testify/mock"

// mockQuerier is an autogenerated mock type for the querier type
type mockQuerier struct {
	mock.Mock
}

// Query provides a mock function with given fields: query
func (_m *mockQuerier) Query(query string) ([]map[string]string, error) {
	ret := _m.Called(query)

	var r0 []map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]map[string]string, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []map[string]string); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockQuerier interface {
	mock.TestingT
	Cleanup(func())
}

// newMockQuerier creates a new instance of mockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockQuerier(t mockConstructorTestingTnewMockQuerier) *mockQuerier {
	mock := &mockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
