run:
  skip-dirs:
    - test-cmds
  timeout: 2m

linters:
  enable:
    - bodyclose
    - deadcode
    - gofmt
    - govet
    - misspell
    - nakedret
    - sqlclosecheck
    - unconvert
  disable:
    - errcheck
    - gosec
    - gosimple
    - ineffassign
    - interfacer
    - maligned
    - noctx
    - staticcheck
    - structcheck
    - unused
    - varcheck

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false
