run:
  skip-dirs:
    - test-cmds
  timeout: 5m

linters:
  enable:
    - bodyclose
    - containedctx
    - unused
    - gofmt
    - govet
    - misspell
    - nakedret
    - sqlclosecheck
    - unconvert
    - paralleltest
    - sloglint
    - revive
  disable:
    - errcheck
    - gosec
    - gosimple
    - ineffassign
    - interfacer
    - maligned
    - noctx
    - staticcheck
    - structcheck
    - varcheck

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false
  sloglint:
    kv-only: true
    context-only: true
    key-naming-case: snake
    static-msg: true
  revive:
    rules:
      - name: superfluous-else
        severity: warning
        disabled: false
        arguments:
          - "preserveScope"

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
