run:
  skip-dirs:
    - test-cmds
  timeout: 5m

linters:
  enable:
    - bodyclose
    - containedctx
    - forbidigo
    - gofmt
    - govet
    - ineffassign
    - misspell
    - nakedret
    - paralleltest
    - revive
    # - sloglint # TODO -- re-enable once golangci-lint bumps to sloglint v0.7.1
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  disable:
    - errcheck
    - gosec
    - gosimple
    - noctx

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false
  forbidigo:
    forbid:
      - p: ^exec\.Command.*$
        msg: use ee/allowedcmd functions instead
      - p: ^os\.Exit.*$
        msg: do not use os.Exit so that launcher can shut down gracefully
      - p: ^logutil\.Fatal.*$
        msg: do not use logutil.Fatal so that launcher can shut down gracefully
      - p: ^panic.*$
        msg: do not use panic so that launcher can shut down gracefully
  sloglint:
    kv-only: true
    context-only: true
    key-naming-case: snake
    static-msg: true
  revive:
    rules:
      - name: superfluous-else
        severity: warning
        disabled: false
        arguments:
          - "preserveScope"
      - name: package-comments
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: error-return
        disabled: false
      - name: errorf
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: early-return
        disabled: false
      - name: confusing-naming
        disabled: false
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
