run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - containedctx
    - forbidigo
    - gofmt
    - govet
    - ineffassign
    - misspell
    - nakedret
    - paralleltest
    - revive
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  disable:
    - errcheck
    - gosec
    - gosimple
    - noctx

linters-settings:
  errcheck:
    exclude-functions: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  forbidigo:
    forbid:
      - p: ^exec\.Command.*$
        msg: use ee/allowedcmd functions instead
      - p: ^os\.Exit.*$
        msg: do not use os.Exit so that launcher can shut down gracefully
      - p: ^logutil\.Fatal.*$
        msg: do not use logutil.Fatal so that launcher can shut down gracefully
      - p: ^panic.*$
        msg: do not use panic so that launcher can shut down gracefully
      - p: ^go func.*$
        msg: use gowrapper.Go() instead of raw goroutines for proper panic handling
      - p: \.Cmd\.(Run|Start|Output|CombinedOutput)
        msg: "Do not call embedded exec.Cmd methods directly on TracedCmd; call TracedCmd.Run(), TracedCmd.Start(), etc. instead"
  sloglint:
    kv-only: true
    context: "all"
    key-naming-case: snake
    static-msg: true
  revive:
    rules:
      - name: superfluous-else
        severity: warning
        disabled: false
        arguments:
          - "preserveScope"
      - name: package-comments
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: error-return
        disabled: false
      - name: errorf
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: early-return
        disabled: false
      - name: confusing-naming
        disabled: false
      - name: defer
        disabled: false
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
  exclude-dirs:
    - test-cmds
