language: go

go:
  - 1.11.x

os:
  - linux
  - osx

stages:
  - Compile
#  - test
#  - deploy


jobs:
  include:
    - stage: "Compile"
      name: "Deps"
      script: make deps
    - name: "build"
      script: make -j 
