language: go

go:
  - 1.11.x

os:
  - linux
  - osx

stages:
  - Compile
  - Test
#  - deploy


jobs:
  include:
    - stage: "Compile"
      name: "deps & build"
      script: make deps build
    - stage: "Test"
      name: "test"
      script: make deps test
