language: go

go:
  - 1.11.x

os:
  - linux
  - osx

stages:
  - Compile
  - Test
#  - deploy


jobs:
  include:
    - stage: "Compile"
      name: "deps"
      script: make deps
    - name: "build"
      script: make
    - stage: "Test"
      name: "test"
      script: make test
