# Use containers, not VMs
sudo: false

notifications:
  email: false

language: go

go:
  - 1.11.x

env:
  global:
    - SKIP_TEST_MDM=true
  matrix:
    - TRAVISTARGET=lint
    - TRAVISTARGET=build
    - TRAVISTARGET=test
    - TRAVISTARGET=package-builder
  
os:
  - linux
  - osx

install:
  - make deps

script:
   - make -j $TRAVISTARGET

