# Use containers, not VMs
sudo: false

notifications:
  email: false

language: go

go:
  - 1.11.x

env:
  - SKIP_TEST_MDM=true
  
os:
  - linux
  - osx

install:
  - make deps

script:
   - make build
   - make test

