# Use containers, not VMs
sudo: false

# Don't email me the results of the test runs.
notifications:
  email: false

language: go

go:
  - 1.11.x

os:
  - linux
  - osx

install:
  - make deps

script:
   - make build
   - make test

