# Use containers, not VMs
sudo: false

notifications:
  email: false

language: go

go:
  - 1.11.x

os:
  - linux
  - osx

install:
  - make deps


env:
  global:
    - SKIP_TEST_MDM=true


stages:
  - lint
  - compile
  - test
  - package-builder


jobs:
  include:
    - stage: lint
      script: make -j lint
    - stage: compile
      script: make build
    - stage: test
      script: make test
    - stage: package-builder
      script: make package-builder
