// Code generated by protoc-gen-go. DO NOT EDIT.
// source: launcher.proto

package launcher

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AGENT is added as a new log type, for adding new
// logging capabilities from kolide/agent
type LogCollection_LogType int32

const (
	LogCollection_RESULT LogCollection_LogType = 0
	LogCollection_STATUS LogCollection_LogType = 1
	LogCollection_AGENT  LogCollection_LogType = 2
)

var LogCollection_LogType_name = map[int32]string{
	0: "RESULT",
	1: "STATUS",
	2: "AGENT",
}

var LogCollection_LogType_value = map[string]int32{
	"RESULT": 0,
	"STATUS": 1,
	"AGENT":  2,
}

func (x LogCollection_LogType) String() string {
	return proto.EnumName(LogCollection_LogType_name, int32(x))
}

func (LogCollection_LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{6, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{9, 0}
}

type AgentApiRequest struct {
	NodeKey              string   `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentApiRequest) Reset()         { *m = AgentApiRequest{} }
func (m *AgentApiRequest) String() string { return proto.CompactTextString(m) }
func (*AgentApiRequest) ProtoMessage()    {}
func (*AgentApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{0}
}

func (m *AgentApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentApiRequest.Unmarshal(m, b)
}
func (m *AgentApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentApiRequest.Marshal(b, m, deterministic)
}
func (m *AgentApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentApiRequest.Merge(m, src)
}
func (m *AgentApiRequest) XXX_Size() int {
	return xxx_messageInfo_AgentApiRequest.Size(m)
}
func (m *AgentApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentApiRequest proto.InternalMessageInfo

func (m *AgentApiRequest) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

type AgentApiResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,3,opt,name=node_invalid,json=nodeInvalid,proto3" json:"node_invalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentApiResponse) Reset()         { *m = AgentApiResponse{} }
func (m *AgentApiResponse) String() string { return proto.CompactTextString(m) }
func (*AgentApiResponse) ProtoMessage()    {}
func (*AgentApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{1}
}

func (m *AgentApiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentApiResponse.Unmarshal(m, b)
}
func (m *AgentApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentApiResponse.Marshal(b, m, deterministic)
}
func (m *AgentApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentApiResponse.Merge(m, src)
}
func (m *AgentApiResponse) XXX_Size() int {
	return xxx_messageInfo_AgentApiResponse.Size(m)
}
func (m *AgentApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentApiResponse proto.InternalMessageInfo

func (m *AgentApiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AgentApiResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *AgentApiResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

type EnrollmentRequest struct {
	EnrollSecret         string             `protobuf:"bytes,1,opt,name=enroll_secret,json=enrollSecret,proto3" json:"enroll_secret,omitempty"`
	HostIdentifier       string             `protobuf:"bytes,2,opt,name=host_identifier,json=hostIdentifier,proto3" json:"host_identifier,omitempty"`
	EnrollmentDetails    *EnrollmentDetails `protobuf:"bytes,3,opt,name=enrollment_details,json=enrollmentDetails,proto3" json:"enrollment_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EnrollmentRequest) Reset()         { *m = EnrollmentRequest{} }
func (m *EnrollmentRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollmentRequest) ProtoMessage()    {}
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{2}
}

func (m *EnrollmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentRequest.Unmarshal(m, b)
}
func (m *EnrollmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentRequest.Marshal(b, m, deterministic)
}
func (m *EnrollmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentRequest.Merge(m, src)
}
func (m *EnrollmentRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollmentRequest.Size(m)
}
func (m *EnrollmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentRequest proto.InternalMessageInfo

func (m *EnrollmentRequest) GetEnrollSecret() string {
	if m != nil {
		return m.EnrollSecret
	}
	return ""
}

func (m *EnrollmentRequest) GetHostIdentifier() string {
	if m != nil {
		return m.HostIdentifier
	}
	return ""
}

func (m *EnrollmentRequest) GetEnrollmentDetails() *EnrollmentDetails {
	if m != nil {
		return m.EnrollmentDetails
	}
	return nil
}

type EnrollmentDetails struct {
	OsVersion            string   `protobuf:"bytes,1,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsBuild              string   `protobuf:"bytes,2,opt,name=os_build,json=osBuild,proto3" json:"os_build,omitempty"`
	OsPlatform           string   `protobuf:"bytes,3,opt,name=os_platform,json=osPlatform,proto3" json:"os_platform,omitempty"`
	Hostname             string   `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HardwareVendor       string   `protobuf:"bytes,5,opt,name=hardware_vendor,json=hardwareVendor,proto3" json:"hardware_vendor,omitempty"`
	HardwareModel        string   `protobuf:"bytes,6,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	HardwareSerial       string   `protobuf:"bytes,7,opt,name=hardware_serial,json=hardwareSerial,proto3" json:"hardware_serial,omitempty"`
	OsqueryVersion       string   `protobuf:"bytes,8,opt,name=osquery_version,json=osqueryVersion,proto3" json:"osquery_version,omitempty"`
	LauncherVersion      string   `protobuf:"bytes,9,opt,name=launcher_version,json=launcherVersion,proto3" json:"launcher_version,omitempty"`
	OsName               string   `protobuf:"bytes,10,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsPlatformLike       string   `protobuf:"bytes,11,opt,name=os_platform_like,json=osPlatformLike,proto3" json:"os_platform_like,omitempty"`
	HardwareUuid         string   `protobuf:"bytes,12,opt,name=hardware_uuid,json=hardwareUuid,proto3" json:"hardware_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentDetails) Reset()         { *m = EnrollmentDetails{} }
func (m *EnrollmentDetails) String() string { return proto.CompactTextString(m) }
func (*EnrollmentDetails) ProtoMessage()    {}
func (*EnrollmentDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{3}
}

func (m *EnrollmentDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentDetails.Unmarshal(m, b)
}
func (m *EnrollmentDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentDetails.Marshal(b, m, deterministic)
}
func (m *EnrollmentDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentDetails.Merge(m, src)
}
func (m *EnrollmentDetails) XXX_Size() int {
	return xxx_messageInfo_EnrollmentDetails.Size(m)
}
func (m *EnrollmentDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentDetails.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentDetails proto.InternalMessageInfo

func (m *EnrollmentDetails) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *EnrollmentDetails) GetOsBuild() string {
	if m != nil {
		return m.OsBuild
	}
	return ""
}

func (m *EnrollmentDetails) GetOsPlatform() string {
	if m != nil {
		return m.OsPlatform
	}
	return ""
}

func (m *EnrollmentDetails) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *EnrollmentDetails) GetHardwareVendor() string {
	if m != nil {
		return m.HardwareVendor
	}
	return ""
}

func (m *EnrollmentDetails) GetHardwareModel() string {
	if m != nil {
		return m.HardwareModel
	}
	return ""
}

func (m *EnrollmentDetails) GetHardwareSerial() string {
	if m != nil {
		return m.HardwareSerial
	}
	return ""
}

func (m *EnrollmentDetails) GetOsqueryVersion() string {
	if m != nil {
		return m.OsqueryVersion
	}
	return ""
}

func (m *EnrollmentDetails) GetLauncherVersion() string {
	if m != nil {
		return m.LauncherVersion
	}
	return ""
}

func (m *EnrollmentDetails) GetOsName() string {
	if m != nil {
		return m.OsName
	}
	return ""
}

func (m *EnrollmentDetails) GetOsPlatformLike() string {
	if m != nil {
		return m.OsPlatformLike
	}
	return ""
}

func (m *EnrollmentDetails) GetHardwareUuid() string {
	if m != nil {
		return m.HardwareUuid
	}
	return ""
}

type EnrollmentResponse struct {
	NodeKey              string   `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid,proto3" json:"node_invalid,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentResponse) Reset()         { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()    {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{4}
}

func (m *EnrollmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentResponse.Unmarshal(m, b)
}
func (m *EnrollmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentResponse.Marshal(b, m, deterministic)
}
func (m *EnrollmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentResponse.Merge(m, src)
}
func (m *EnrollmentResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollmentResponse.Size(m)
}
func (m *EnrollmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentResponse proto.InternalMessageInfo

func (m *EnrollmentResponse) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *EnrollmentResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *EnrollmentResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

// kolide/cloud will be generating well-structured json already, so forward
// it along instead of de/re/de-serializing it as a protobuf too
// this might make sense to convert to full proto later
type ConfigResponse struct {
	ConfigJsonBlob       string   `protobuf:"bytes,1,opt,name=config_json_blob,json=configJsonBlob,proto3" json:"config_json_blob,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid,proto3" json:"node_invalid,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{5}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetConfigJsonBlob() string {
	if m != nil {
		return m.ConfigJsonBlob
	}
	return ""
}

func (m *ConfigResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *ConfigResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type LogCollection struct {
	NodeKey              string                `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	LogType              LogCollection_LogType `protobuf:"varint,2,opt,name=log_type,json=logType,proto3,enum=kolide.agent.LogCollection_LogType" json:"log_type,omitempty"`
	Logs                 []*LogCollection_Log  `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	ErrorCode            string                `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LogCollection) Reset()         { *m = LogCollection{} }
func (m *LogCollection) String() string { return proto.CompactTextString(m) }
func (*LogCollection) ProtoMessage()    {}
func (*LogCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{6}
}

func (m *LogCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCollection.Unmarshal(m, b)
}
func (m *LogCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCollection.Marshal(b, m, deterministic)
}
func (m *LogCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCollection.Merge(m, src)
}
func (m *LogCollection) XXX_Size() int {
	return xxx_messageInfo_LogCollection.Size(m)
}
func (m *LogCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCollection.DiscardUnknown(m)
}

var xxx_messageInfo_LogCollection proto.InternalMessageInfo

func (m *LogCollection) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *LogCollection) GetLogType() LogCollection_LogType {
	if m != nil {
		return m.LogType
	}
	return LogCollection_RESULT
}

func (m *LogCollection) GetLogs() []*LogCollection_Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type LogCollection_Log struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCollection_Log) Reset()         { *m = LogCollection_Log{} }
func (m *LogCollection_Log) String() string { return proto.CompactTextString(m) }
func (*LogCollection_Log) ProtoMessage()    {}
func (*LogCollection_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{6, 0}
}

func (m *LogCollection_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCollection_Log.Unmarshal(m, b)
}
func (m *LogCollection_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCollection_Log.Marshal(b, m, deterministic)
}
func (m *LogCollection_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCollection_Log.Merge(m, src)
}
func (m *LogCollection_Log) XXX_Size() int {
	return xxx_messageInfo_LogCollection_Log.Size(m)
}
func (m *LogCollection_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCollection_Log.DiscardUnknown(m)
}

var xxx_messageInfo_LogCollection_Log proto.InternalMessageInfo

func (m *LogCollection_Log) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// a query collection contains many queries
type QueryCollection struct {
	Queries              []*QueryCollection_Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	NodeInvalid          bool                     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid,proto3" json:"node_invalid,omitempty"`
	ErrorCode            string                   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QueryCollection) Reset()         { *m = QueryCollection{} }
func (m *QueryCollection) String() string { return proto.CompactTextString(m) }
func (*QueryCollection) ProtoMessage()    {}
func (*QueryCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{7}
}

func (m *QueryCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCollection.Unmarshal(m, b)
}
func (m *QueryCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCollection.Marshal(b, m, deterministic)
}
func (m *QueryCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollection.Merge(m, src)
}
func (m *QueryCollection) XXX_Size() int {
	return xxx_messageInfo_QueryCollection.Size(m)
}
func (m *QueryCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollection.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollection proto.InternalMessageInfo

func (m *QueryCollection) GetQueries() []*QueryCollection_Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *QueryCollection) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *QueryCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type QueryCollection_Query struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCollection_Query) Reset()         { *m = QueryCollection_Query{} }
func (m *QueryCollection_Query) String() string { return proto.CompactTextString(m) }
func (*QueryCollection_Query) ProtoMessage()    {}
func (*QueryCollection_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{7, 0}
}

func (m *QueryCollection_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCollection_Query.Unmarshal(m, b)
}
func (m *QueryCollection_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCollection_Query.Marshal(b, m, deterministic)
}
func (m *QueryCollection_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollection_Query.Merge(m, src)
}
func (m *QueryCollection_Query) XXX_Size() int {
	return xxx_messageInfo_QueryCollection_Query.Size(m)
}
func (m *QueryCollection_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollection_Query.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollection_Query proto.InternalMessageInfo

func (m *QueryCollection_Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryCollection_Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

// a result collection contains many results
type ResultCollection struct {
	NodeKey              string                     `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Results              []*ResultCollection_Result `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	ErrorCode            string                     `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ResultCollection) Reset()         { *m = ResultCollection{} }
func (m *ResultCollection) String() string { return proto.CompactTextString(m) }
func (*ResultCollection) ProtoMessage()    {}
func (*ResultCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{8}
}

func (m *ResultCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection.Unmarshal(m, b)
}
func (m *ResultCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection.Marshal(b, m, deterministic)
}
func (m *ResultCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection.Merge(m, src)
}
func (m *ResultCollection) XXX_Size() int {
	return xxx_messageInfo_ResultCollection.Size(m)
}
func (m *ResultCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection proto.InternalMessageInfo

func (m *ResultCollection) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *ResultCollection) GetResults() []*ResultCollection_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ResultCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

// status is moved here instead of appearing as a map of id[status]
// on the ResultCollection, as it does in the osq docs
type ResultCollection_Result struct {
	Id                   string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rows                 []*ResultCollection_Result_ResultRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Status               int32                                `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ResultCollection_Result) Reset()         { *m = ResultCollection_Result{} }
func (m *ResultCollection_Result) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result) ProtoMessage()    {}
func (*ResultCollection_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{8, 0}
}

func (m *ResultCollection_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result.Unmarshal(m, b)
}
func (m *ResultCollection_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result.Marshal(b, m, deterministic)
}
func (m *ResultCollection_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result.Merge(m, src)
}
func (m *ResultCollection_Result) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result.Size(m)
}
func (m *ResultCollection_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result proto.InternalMessageInfo

func (m *ResultCollection_Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResultCollection_Result) GetRows() []*ResultCollection_Result_ResultRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ResultCollection_Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ResultCollection_Result_ResultRow struct {
	Columns              []*ResultCollection_Result_ResultRow_Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ResultCollection_Result_ResultRow) Reset()         { *m = ResultCollection_Result_ResultRow{} }
func (m *ResultCollection_Result_ResultRow) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result_ResultRow) ProtoMessage()    {}
func (*ResultCollection_Result_ResultRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{8, 0, 0}
}

func (m *ResultCollection_Result_ResultRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Unmarshal(m, b)
}
func (m *ResultCollection_Result_ResultRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Marshal(b, m, deterministic)
}
func (m *ResultCollection_Result_ResultRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result_ResultRow.Merge(m, src)
}
func (m *ResultCollection_Result_ResultRow) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Size(m)
}
func (m *ResultCollection_Result_ResultRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result_ResultRow.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result_ResultRow proto.InternalMessageInfo

func (m *ResultCollection_Result_ResultRow) GetColumns() []*ResultCollection_Result_ResultRow_Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ResultCollection_Result_ResultRow_Column struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultCollection_Result_ResultRow_Column) Reset() {
	*m = ResultCollection_Result_ResultRow_Column{}
}
func (m *ResultCollection_Result_ResultRow_Column) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result_ResultRow_Column) ProtoMessage()    {}
func (*ResultCollection_Result_ResultRow_Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{8, 0, 0, 0}
}

func (m *ResultCollection_Result_ResultRow_Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Unmarshal(m, b)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Marshal(b, m, deterministic)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Merge(m, src)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Size(m)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result_ResultRow_Column.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result_ResultRow_Column proto.InternalMessageInfo

func (m *ResultCollection_Result_ResultRow_Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResultCollection_Result_ResultRow_Column) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=kolide.agent.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbaa048d93cc1f79, []int{9}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("kolide.agent.LogCollection_LogType", LogCollection_LogType_name, LogCollection_LogType_value)
	proto.RegisterEnum("kolide.agent.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*AgentApiRequest)(nil), "kolide.agent.AgentApiRequest")
	proto.RegisterType((*AgentApiResponse)(nil), "kolide.agent.AgentApiResponse")
	proto.RegisterType((*EnrollmentRequest)(nil), "kolide.agent.EnrollmentRequest")
	proto.RegisterType((*EnrollmentDetails)(nil), "kolide.agent.EnrollmentDetails")
	proto.RegisterType((*EnrollmentResponse)(nil), "kolide.agent.EnrollmentResponse")
	proto.RegisterType((*ConfigResponse)(nil), "kolide.agent.ConfigResponse")
	proto.RegisterType((*LogCollection)(nil), "kolide.agent.LogCollection")
	proto.RegisterType((*LogCollection_Log)(nil), "kolide.agent.LogCollection.Log")
	proto.RegisterType((*QueryCollection)(nil), "kolide.agent.QueryCollection")
	proto.RegisterType((*QueryCollection_Query)(nil), "kolide.agent.QueryCollection.Query")
	proto.RegisterType((*ResultCollection)(nil), "kolide.agent.ResultCollection")
	proto.RegisterType((*ResultCollection_Result)(nil), "kolide.agent.ResultCollection.Result")
	proto.RegisterType((*ResultCollection_Result_ResultRow)(nil), "kolide.agent.ResultCollection.Result.ResultRow")
	proto.RegisterType((*ResultCollection_Result_ResultRow_Column)(nil), "kolide.agent.ResultCollection.Result.ResultRow.Column")
	proto.RegisterType((*HealthCheckResponse)(nil), "kolide.agent.HealthCheckResponse")
}

func init() { proto.RegisterFile("launcher.proto", fileDescriptor_fbaa048d93cc1f79) }

var fileDescriptor_fbaa048d93cc1f79 = []byte{
	// 1021 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0x93, 0x26, 0x4e, 0x5e, 0xda, 0xd4, 0x1d, 0x56, 0xe0, 0x0d, 0x74, 0xb7, 0xeb, 0xd5,
	0x8a, 0x22, 0x2d, 0x41, 0xea, 0x4a, 0x1c, 0x90, 0x00, 0xb5, 0xa1, 0x2a, 0x65, 0x43, 0xb6, 0x75,
	0xd2, 0x82, 0xb8, 0x58, 0x4e, 0x3c, 0x4d, 0x87, 0x4e, 0x3c, 0xa9, 0xc7, 0x4e, 0x15, 0x89, 0x3b,
	0xe2, 0xc8, 0x11, 0xbe, 0x05, 0x9f, 0x00, 0xf1, 0xa5, 0x38, 0xa3, 0x19, 0xcf, 0xb8, 0x89, 0x43,
	0xda, 0x22, 0xf6, 0x36, 0xef, 0x37, 0xbf, 0xf7, 0xd7, 0xef, 0xbd, 0x31, 0x34, 0xa8, 0x9f, 0x84,
	0xc3, 0x4b, 0x1c, 0xb5, 0x26, 0x11, 0x8b, 0x19, 0x5a, 0xbf, 0x62, 0x94, 0x04, 0xb8, 0xe5, 0x8f,
	0x70, 0x18, 0x3b, 0x2f, 0x61, 0x73, 0x5f, 0x1c, 0xf6, 0x27, 0xc4, 0xc5, 0xd7, 0x09, 0xe6, 0x31,
	0x7a, 0x0c, 0xd5, 0x90, 0x05, 0xd8, 0xbb, 0xc2, 0x33, 0xdb, 0xd8, 0x31, 0x76, 0x6b, 0xae, 0x29,
	0xe4, 0xd7, 0x78, 0xe6, 0x84, 0x60, 0xdd, 0xb2, 0xf9, 0x84, 0x85, 0x1c, 0x23, 0x1b, 0xcc, 0x31,
	0xe6, 0xdc, 0x1f, 0x61, 0xcd, 0x56, 0x22, 0xda, 0x06, 0xc0, 0x51, 0xc4, 0x22, 0x6f, 0xc8, 0x02,
	0x6c, 0x17, 0xe5, 0x65, 0x4d, 0x22, 0x6d, 0x16, 0x60, 0xf4, 0x0c, 0xd6, 0xa5, 0x1f, 0x12, 0x4e,
	0x7d, 0x4a, 0x02, 0xbb, 0xb4, 0x63, 0xec, 0x56, 0xdd, 0xba, 0xc0, 0x8e, 0x53, 0xc8, 0xf9, 0xc3,
	0x80, 0xad, 0xc3, 0x30, 0x62, 0x94, 0x8e, 0x71, 0x18, 0xeb, 0x00, 0x9f, 0xc3, 0x06, 0x96, 0xa0,
	0xc7, 0xf1, 0x30, 0xc2, 0xb1, 0xf2, 0xbb, 0x9e, 0x82, 0x3d, 0x89, 0xa1, 0x0f, 0x61, 0xf3, 0x92,
	0xf1, 0xd8, 0x23, 0x01, 0x0e, 0x63, 0x72, 0x41, 0x70, 0xa4, 0x22, 0x68, 0x08, 0xf8, 0x38, 0x43,
	0x51, 0x17, 0x10, 0xce, 0x5c, 0x78, 0x01, 0x8e, 0x7d, 0x42, 0xb9, 0x0c, 0xa6, 0xbe, 0xf7, 0xb4,
	0x35, 0x5f, 0xac, 0xd6, 0x6d, 0x28, 0x5f, 0xa5, 0x34, 0x77, 0x0b, 0xe7, 0x21, 0xe7, 0xcf, 0xd2,
	0x7c, 0xcc, 0x0a, 0x15, 0xb5, 0x60, 0xdc, 0x9b, 0xe2, 0x88, 0x13, 0x16, 0xaa, 0x80, 0x6b, 0x8c,
	0x9f, 0xa7, 0x80, 0xa8, 0x39, 0xe3, 0xde, 0x20, 0x21, 0x34, 0x50, 0x61, 0x9a, 0x8c, 0x1f, 0x08,
	0x11, 0x3d, 0x85, 0x3a, 0xe3, 0xde, 0x84, 0xfa, 0xf1, 0x05, 0x8b, 0xc6, 0x32, 0xb0, 0x9a, 0x0b,
	0x8c, 0x9f, 0x28, 0x04, 0x35, 0xa1, 0x2a, 0x52, 0x0a, 0xfd, 0x31, 0xb6, 0xd7, 0xe4, 0x6d, 0x26,
	0xcb, 0x2a, 0xf8, 0x51, 0x70, 0xe3, 0x47, 0xd8, 0x9b, 0xe2, 0x30, 0x60, 0x91, 0x5d, 0x56, 0x55,
	0x50, 0xf0, 0xb9, 0x44, 0xd1, 0x0b, 0xc8, 0x10, 0x6f, 0xcc, 0x02, 0x4c, 0xed, 0x8a, 0xe4, 0x6d,
	0x68, 0xf4, 0x5b, 0x01, 0x2e, 0xd8, 0xe3, 0x38, 0x22, 0x3e, 0xb5, 0xcd, 0x45, 0x7b, 0x3d, 0x89,
	0x0a, 0x22, 0xe3, 0xd7, 0x09, 0x8e, 0x66, 0x59, 0xd2, 0xd5, 0x94, 0xa8, 0x60, 0x9d, 0xf9, 0x47,
	0x60, 0xe9, 0x06, 0xcd, 0x98, 0x35, 0xc9, 0xdc, 0xd4, 0xb8, 0xa6, 0xbe, 0x07, 0x26, 0xe3, 0x9e,
	0xcc, 0x13, 0x24, 0xa3, 0xc2, 0x78, 0x57, 0x64, 0xb9, 0x0b, 0xd6, 0x5c, 0x89, 0x3c, 0x4a, 0xae,
	0xb0, 0x5d, 0xd7, 0xde, 0x74, 0x9d, 0x3a, 0xe4, 0x0a, 0x8b, 0xd6, 0xc9, 0xe2, 0x4f, 0x12, 0x12,
	0xd8, 0xeb, 0x69, 0xeb, 0x68, 0xf0, 0x2c, 0x21, 0x81, 0x73, 0x0d, 0x68, 0xbe, 0xe9, 0x54, 0x9f,
	0xaf, 0x1e, 0x8b, 0xa5, 0x4e, 0x2e, 0x2e, 0x75, 0x72, 0x6e, 0x16, 0x4a, 0xb9, 0x59, 0x70, 0x7e,
	0x82, 0x46, 0x9b, 0x85, 0x17, 0x64, 0x94, 0xb9, 0xdb, 0x05, 0x6b, 0x28, 0x11, 0xef, 0x47, 0xce,
	0x42, 0x6f, 0x40, 0xd9, 0x40, 0xb9, 0x6d, 0xa4, 0xf8, 0x37, 0x9c, 0x85, 0x07, 0x94, 0x0d, 0xde,
	0x82, 0xf7, 0x9f, 0x8b, 0xb0, 0xd1, 0x61, 0xa3, 0x36, 0xa3, 0x14, 0x0f, 0x63, 0xd5, 0x8f, 0xab,
	0x92, 0xfd, 0x02, 0xaa, 0x94, 0x8d, 0xbc, 0x78, 0x36, 0x49, 0x67, 0xba, 0xb1, 0xf7, 0x7c, 0x71,
	0x4a, 0x16, 0x2c, 0x09, 0xa9, 0x3f, 0x9b, 0x60, 0xd7, 0xa4, 0xe9, 0x01, 0xbd, 0x82, 0x35, 0xca,
	0x46, 0x62, 0xc2, 0x4a, 0xcb, 0x13, 0xb6, 0xa4, 0xeb, 0x4a, 0x72, 0x2e, 0x81, 0xb5, 0x5c, 0x02,
	0xcd, 0xc7, 0x50, 0xea, 0xb0, 0x11, 0x42, 0xb0, 0x16, 0xf8, 0xb1, 0xaf, 0x22, 0x96, 0x67, 0xe7,
	0x25, 0x98, 0x2a, 0x04, 0x04, 0x50, 0x71, 0x0f, 0x7b, 0x67, 0x9d, 0xbe, 0x55, 0x10, 0xe7, 0x5e,
	0x7f, 0xbf, 0x7f, 0xd6, 0xb3, 0x0c, 0x54, 0x83, 0xf2, 0xfe, 0xd1, 0x61, 0xb7, 0x6f, 0x15, 0x9d,
	0xbf, 0x0c, 0xd8, 0x3c, 0x15, 0xed, 0x39, 0x57, 0x8b, 0xcf, 0xc1, 0x14, 0x1d, 0x4b, 0x30, 0xb7,
	0x0d, 0x19, 0x73, 0x2e, 0xdf, 0x1c, 0x3f, 0x95, 0x5d, 0xad, 0xf3, 0xff, 0x3f, 0x4f, 0xf3, 0x63,
	0x28, 0x4b, 0x9b, 0xa8, 0x01, 0x45, 0x12, 0xa8, 0xec, 0x8a, 0x24, 0x40, 0x8f, 0xa0, 0x2c, 0x67,
	0x49, 0xad, 0x8c, 0x54, 0x70, 0x7e, 0x2b, 0x81, 0xe5, 0x62, 0x9e, 0xd0, 0xf8, 0x61, 0x1f, 0xf4,
	0x4b, 0x30, 0x23, 0x49, 0xe7, 0x76, 0x51, 0xe6, 0xf7, 0x62, 0x31, 0xbf, 0xbc, 0x2d, 0x05, 0xb8,
	0x5a, 0xeb, 0xbe, 0xf0, 0x7f, 0x29, 0x42, 0x25, 0x55, 0x59, 0x4a, 0xa0, 0x0d, 0x6b, 0x11, 0xbb,
	0xd1, 0x7e, 0x3f, 0x79, 0x90, 0x5f, 0xed, 0x9e, 0xdd, 0xb8, 0x52, 0x19, 0xbd, 0x0b, 0x15, 0x1e,
	0xfb, 0x71, 0x92, 0x2e, 0xed, 0xb2, 0xab, 0xa4, 0xe6, 0xaf, 0x06, 0xd4, 0x32, 0x2e, 0x3a, 0x01,
	0x73, 0xc8, 0x68, 0x32, 0x0e, 0xf5, 0x57, 0xfc, 0xf4, 0x3f, 0x7a, 0x6b, 0xb5, 0xa5, 0xba, 0xab,
	0xcd, 0x34, 0xf7, 0xa0, 0x92, 0x42, 0xa2, 0xef, 0xe4, 0x56, 0x52, 0x7d, 0x27, 0x37, 0xef, 0x23,
	0x28, 0x4f, 0x7d, 0x9a, 0xe8, 0x77, 0x2f, 0x15, 0x9c, 0xdf, 0x0d, 0x78, 0xe7, 0x6b, 0xec, 0xd3,
	0xf8, 0xb2, 0x7d, 0x89, 0x87, 0x57, 0xd9, 0xb4, 0x1f, 0x65, 0x39, 0x18, 0x72, 0xa4, 0x72, 0xa5,
	0xf8, 0x17, 0x95, 0x56, 0x0f, 0x47, 0x53, 0x12, 0x8e, 0x7a, 0x52, 0x4d, 0x27, 0xed, 0x7c, 0x06,
	0x1b, 0x0b, 0x17, 0xa8, 0x0e, 0xe6, 0x59, 0xf7, 0x75, 0xf7, 0xcd, 0x77, 0x5d, 0xab, 0x20, 0x84,
	0xde, 0xa1, 0x7b, 0x7e, 0xdc, 0x3d, 0xb2, 0x0c, 0xb4, 0x09, 0xf5, 0xee, 0x9b, 0xbe, 0xa7, 0x81,
	0xe2, 0xde, 0xdf, 0x25, 0x28, 0xed, 0x4f, 0x08, 0xfa, 0x1e, 0xb6, 0xd4, 0x53, 0x7b, 0xbb, 0x06,
	0xd1, 0xca, 0xa7, 0x50, 0x51, 0x9b, 0x3b, 0xab, 0x09, 0x69, 0xc4, 0x4e, 0x01, 0x75, 0x61, 0x43,
	0xd1, 0xd3, 0x6d, 0x87, 0xb6, 0x17, 0x95, 0x72, 0xbf, 0x22, 0xcd, 0x0f, 0x16, 0xaf, 0x17, 0x57,
	0xa4, 0x53, 0x40, 0x27, 0xd0, 0x50, 0xd4, 0x53, 0x35, 0x6d, 0xf7, 0x18, 0xdc, 0xbe, 0x73, 0x74,
	0x9d, 0x02, 0xea, 0x40, 0xfd, 0x24, 0x19, 0x50, 0xc2, 0x2f, 0x3b, 0x62, 0xef, 0xbc, 0x7f, 0xc7,
	0x7a, 0x6a, 0x3e, 0x59, 0xe5, 0x2b, 0x8b, 0xcf, 0x85, 0x86, 0xb2, 0xe6, 0xaa, 0x59, 0x79, 0x72,
	0x77, 0xd7, 0x3d, 0xc0, 0xe6, 0x29, 0xd4, 0x65, 0x23, 0xa4, 0x3d, 0x71, 0x5f, 0xc2, 0xcf, 0xee,
	0x6d, 0x24, 0xa7, 0x70, 0x00, 0x3f, 0x54, 0xf5, 0x5b, 0x3b, 0xa8, 0xc8, 0xbf, 0xc4, 0x57, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xcb, 0x28, 0xf0, 0x37, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	// Attempt to enroll a host with kolide/cloud
	RequestEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	// request an updated configuration from kolide/cloud
	// a generic request object is sent
	RequestConfig(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// request/pull Dist queries from kolide/cloud
	// a generic request object is sent
	RequestQueries(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*QueryCollection, error)
	// publish logs from osqueryd to kolide/cloud
	// a generic response object is returned
	PublishLogs(ctx context.Context, in *LogCollection, opts ...grpc.CallOption) (*AgentApiResponse, error)
	// publish results from Dist queries to kolide/cloud
	// a generic response object is returned
	PublishResults(ctx context.Context, in *ResultCollection, opts ...grpc.CallOption) (*AgentApiResponse, error)
	// check the health of the GRPC server
	// a value indicating healthiness is returned
	// if you don't hear from this endpoint assume the worst
	CheckHealth(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) RequestEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/RequestEnrollment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RequestConfig(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/RequestConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RequestQueries(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*QueryCollection, error) {
	out := new(QueryCollection)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/RequestQueries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PublishLogs(ctx context.Context, in *LogCollection, opts ...grpc.CallOption) (*AgentApiResponse, error) {
	out := new(AgentApiResponse)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/PublishLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PublishResults(ctx context.Context, in *ResultCollection, opts ...grpc.CallOption) (*AgentApiResponse, error) {
	out := new(AgentApiResponse)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/PublishResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CheckHealth(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/kolide.agent.Api/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	// Attempt to enroll a host with kolide/cloud
	RequestEnrollment(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error)
	// request an updated configuration from kolide/cloud
	// a generic request object is sent
	RequestConfig(context.Context, *AgentApiRequest) (*ConfigResponse, error)
	// request/pull Dist queries from kolide/cloud
	// a generic request object is sent
	RequestQueries(context.Context, *AgentApiRequest) (*QueryCollection, error)
	// publish logs from osqueryd to kolide/cloud
	// a generic response object is returned
	PublishLogs(context.Context, *LogCollection) (*AgentApiResponse, error)
	// publish results from Dist queries to kolide/cloud
	// a generic response object is returned
	PublishResults(context.Context, *ResultCollection) (*AgentApiResponse, error)
	// check the health of the GRPC server
	// a value indicating healthiness is returned
	// if you don't hear from this endpoint assume the worst
	CheckHealth(context.Context, *AgentApiRequest) (*HealthCheckResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) RequestEnrollment(ctx context.Context, req *EnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestEnrollment not implemented")
}
func (*UnimplementedApiServer) RequestConfig(ctx context.Context, req *AgentApiRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestConfig not implemented")
}
func (*UnimplementedApiServer) RequestQueries(ctx context.Context, req *AgentApiRequest) (*QueryCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestQueries not implemented")
}
func (*UnimplementedApiServer) PublishLogs(ctx context.Context, req *LogCollection) (*AgentApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishLogs not implemented")
}
func (*UnimplementedApiServer) PublishResults(ctx context.Context, req *ResultCollection) (*AgentApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishResults not implemented")
}
func (*UnimplementedApiServer) CheckHealth(ctx context.Context, req *AgentApiRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_RequestEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RequestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestConfig(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RequestQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestQueries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestQueries(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PublishLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/PublishLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishLogs(ctx, req.(*LogCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PublishResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/PublishResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishResults(ctx, req.(*ResultCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CheckHealth(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kolide.agent.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestEnrollment",
			Handler:    _Api_RequestEnrollment_Handler,
		},
		{
			MethodName: "RequestConfig",
			Handler:    _Api_RequestConfig_Handler,
		},
		{
			MethodName: "RequestQueries",
			Handler:    _Api_RequestQueries_Handler,
		},
		{
			MethodName: "PublishLogs",
			Handler:    _Api_PublishLogs_Handler,
		},
		{
			MethodName: "PublishResults",
			Handler:    _Api_PublishResults_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _Api_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launcher.proto",
}
