// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHostResolver creates a new instance of HostResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHostResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *HostResolver {
	mock := &HostResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HostResolver is an autogenerated mock type for the HostResolver type
type HostResolver struct {
	mock.Mock
}

type HostResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *HostResolver) EXPECT() *HostResolver_Expecter {
	return &HostResolver_Expecter{mock: &_m.Mock}
}

// LookupHost provides a mock function for the type HostResolver
func (_mock *HostResolver) LookupHost(ctx context.Context, host string) ([]string, error) {
	ret := _mock.Called(ctx, host)

	if len(ret) == 0 {
		panic("no return value specified for LookupHost")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, host)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, host)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HostResolver_LookupHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupHost'
type HostResolver_LookupHost_Call struct {
	*mock.Call
}

// LookupHost is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
func (_e *HostResolver_Expecter) LookupHost(ctx interface{}, host interface{}) *HostResolver_LookupHost_Call {
	return &HostResolver_LookupHost_Call{Call: _e.mock.On("LookupHost", ctx, host)}
}

func (_c *HostResolver_LookupHost_Call) Run(run func(ctx context.Context, host string)) *HostResolver_LookupHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HostResolver_LookupHost_Call) Return(strings []string, err error) *HostResolver_LookupHost_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *HostResolver_LookupHost_Call) RunAndReturn(run func(ctx context.Context, host string) ([]string, error)) *HostResolver_LookupHost_Call {
	_c.Call.Return(run)
	return _c
}
