// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/kolide/launcher/ee/agent/types"
	mock "github.com/stretchr/testify/mock"
)

// NewFlarer creates a new instance of Flarer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlarer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Flarer {
	mock := &Flarer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Flarer is an autogenerated mock type for the flarer type
type Flarer struct {
	mock.Mock
}

type Flarer_Expecter struct {
	mock *mock.Mock
}

func (_m *Flarer) EXPECT() *Flarer_Expecter {
	return &Flarer_Expecter{mock: &_m.Mock}
}

// RunFlare provides a mock function for the type Flarer
func (_mock *Flarer) RunFlare(ctx context.Context, k types.Knapsack, flareStream io.WriteCloser) error {
	ret := _mock.Called(ctx, k, flareStream)

	if len(ret) == 0 {
		panic("no return value specified for RunFlare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Knapsack, io.WriteCloser) error); ok {
		r0 = returnFunc(ctx, k, flareStream)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Flarer_RunFlare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunFlare'
type Flarer_RunFlare_Call struct {
	*mock.Call
}

// RunFlare is a helper method to define mock.On call
//   - ctx context.Context
//   - k types.Knapsack
//   - flareStream io.WriteCloser
func (_e *Flarer_Expecter) RunFlare(ctx interface{}, k interface{}, flareStream interface{}) *Flarer_RunFlare_Call {
	return &Flarer_RunFlare_Call{Call: _e.mock.On("RunFlare", ctx, k, flareStream)}
}

func (_c *Flarer_RunFlare_Call) Run(run func(ctx context.Context, k types.Knapsack, flareStream io.WriteCloser)) *Flarer_RunFlare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Knapsack
		if args[1] != nil {
			arg1 = args[1].(types.Knapsack)
		}
		var arg2 io.WriteCloser
		if args[2] != nil {
			arg2 = args[2].(io.WriteCloser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Flarer_RunFlare_Call) Return(err error) *Flarer_RunFlare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Flarer_RunFlare_Call) RunAndReturn(run func(ctx context.Context, k types.Knapsack, flareStream io.WriteCloser) error) *Flarer_RunFlare_Call {
	_c.Call.Return(run)
	return _c
}
