// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewDataProvider creates a new instance of DataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataProvider {
	mock := &DataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataProvider is an autogenerated mock type for the dataProvider type
type DataProvider struct {
	mock.Mock
}

type DataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DataProvider) EXPECT() *DataProvider_Expecter {
	return &DataProvider_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type DataProvider
func (_mock *DataProvider) GetConfig(ctx context.Context) (io.Reader, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (io.Reader, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) io.Reader); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type DataProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataProvider_Expecter) GetConfig(ctx interface{}) *DataProvider_GetConfig_Call {
	return &DataProvider_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx)}
}

func (_c *DataProvider_GetConfig_Call) Run(run func(ctx context.Context)) *DataProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DataProvider_GetConfig_Call) Return(reader io.Reader, err error) *DataProvider_GetConfig_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *DataProvider_GetConfig_Call) RunAndReturn(run func(ctx context.Context) (io.Reader, error)) *DataProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubsystemData provides a mock function for the type DataProvider
func (_mock *DataProvider) GetSubsystemData(ctx context.Context, hash string) (io.Reader, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetSubsystemData")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.Reader, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.Reader); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataProvider_GetSubsystemData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubsystemData'
type DataProvider_GetSubsystemData_Call struct {
	*mock.Call
}

// GetSubsystemData is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *DataProvider_Expecter) GetSubsystemData(ctx interface{}, hash interface{}) *DataProvider_GetSubsystemData_Call {
	return &DataProvider_GetSubsystemData_Call{Call: _e.mock.On("GetSubsystemData", ctx, hash)}
}

func (_c *DataProvider_GetSubsystemData_Call) Run(run func(ctx context.Context, hash string)) *DataProvider_GetSubsystemData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataProvider_GetSubsystemData_Call) Return(reader io.Reader, err error) *DataProvider_GetSubsystemData_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *DataProvider_GetSubsystemData_Call) RunAndReturn(run func(ctx context.Context, hash string) (io.Reader, error)) *DataProvider_GetSubsystemData_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type DataProvider
func (_mock *DataProvider) SendMessage(ctx context.Context, method string, params any) error {
	ret := _mock.Called(ctx, method, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, method, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DataProvider_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type DataProvider_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - params any
func (_e *DataProvider_Expecter) SendMessage(ctx interface{}, method interface{}, params interface{}) *DataProvider_SendMessage_Call {
	return &DataProvider_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, method, params)}
}

func (_c *DataProvider_SendMessage_Call) Run(run func(ctx context.Context, method string, params any)) *DataProvider_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataProvider_SendMessage_Call) Return(err error) *DataProvider_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DataProvider_SendMessage_Call) RunAndReturn(run func(ctx context.Context, method string, params any) error) *DataProvider_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
