// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/kolide/launcher/ee/agent/flags/keys"
	mock "github.com/stretchr/testify/mock"
)

// NewFlagsChangeObserver creates a new instance of FlagsChangeObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagsChangeObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagsChangeObserver {
	mock := &FlagsChangeObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FlagsChangeObserver is an autogenerated mock type for the FlagsChangeObserver type
type FlagsChangeObserver struct {
	mock.Mock
}

type FlagsChangeObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *FlagsChangeObserver) EXPECT() *FlagsChangeObserver_Expecter {
	return &FlagsChangeObserver_Expecter{mock: &_m.Mock}
}

// FlagsChanged provides a mock function for the type FlagsChangeObserver
func (_mock *FlagsChangeObserver) FlagsChanged(ctx context.Context, flagKeys ...keys.FlagKey) {
	// keys.FlagKey
	_va := make([]interface{}, len(flagKeys))
	for _i := range flagKeys {
		_va[_i] = flagKeys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// FlagsChangeObserver_FlagsChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlagsChanged'
type FlagsChangeObserver_FlagsChanged_Call struct {
	*mock.Call
}

// FlagsChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKeys ...keys.FlagKey
func (_e *FlagsChangeObserver_Expecter) FlagsChanged(ctx interface{}, flagKeys ...interface{}) *FlagsChangeObserver_FlagsChanged_Call {
	return &FlagsChangeObserver_FlagsChanged_Call{Call: _e.mock.On("FlagsChanged",
		append([]interface{}{ctx}, flagKeys...)...)}
}

func (_c *FlagsChangeObserver_FlagsChanged_Call) Run(run func(ctx context.Context, flagKeys ...keys.FlagKey)) *FlagsChangeObserver_FlagsChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []keys.FlagKey
		variadicArgs := make([]keys.FlagKey, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(keys.FlagKey)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *FlagsChangeObserver_FlagsChanged_Call) Return() *FlagsChangeObserver_FlagsChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *FlagsChangeObserver_FlagsChanged_Call) RunAndReturn(run func(ctx context.Context, flagKeys ...keys.FlagKey)) *FlagsChangeObserver_FlagsChanged_Call {
	_c.Run(run)
	return _c
}
