// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	keys "github.com/kolide/launcher/ee/agent/flags/keys"
	mock "github.com/stretchr/testify/mock"
)

// FlagsChangeObserver is an autogenerated mock type for the FlagsChangeObserver type
type FlagsChangeObserver struct {
	mock.Mock
}

// FlagsChanged provides a mock function with given fields: ctx, flagKeys
func (_m *FlagsChangeObserver) FlagsChanged(ctx context.Context, flagKeys ...keys.FlagKey) {
	_va := make([]interface{}, len(flagKeys))
	for _i := range flagKeys {
		_va[_i] = flagKeys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// NewFlagsChangeObserver creates a new instance of FlagsChangeObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagsChangeObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagsChangeObserver {
	mock := &FlagsChangeObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
