// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type Querier
func (_mock *Querier) Query(query string) ([]map[string]string, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]map[string]string, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []map[string]string); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Querier_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
func (_e *Querier_Expecter) Query(query interface{}) *Querier_Query_Call {
	return &Querier_Query_Call{Call: _e.mock.On("Query", query)}
}

func (_c *Querier_Query_Call) Run(run func(query string)) *Querier_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Querier_Query_Call) Return(stringToStrings []map[string]string, err error) *Querier_Query_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *Querier_Query_Call) RunAndReturn(run func(query string) ([]map[string]string, error)) *Querier_Query_Call {
	_c.Call.Return(run)
	return _c
}
