steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--tag=gcr.io/kolide-public-containers/launcher-builder:1.11',
            '.'
        ]

images:
        - 'gcr.io/kolide-public-containers/launcher-builder:1.11'
