# This config extends the default gitleaks config with some additional settings
# to avoid false positives.
title = "Kolide secretscan config"

[extend]
useDefault = true

# Ignore K8s Sealed Secrets
# https://github.com/gitleaks/gitleaks/issues/1728
[[rules]]
id = "generic-api-key"
[[rules.allowlists]]
condition = "AND"
regexes = ['''Ag[a-zA-Z0-9+/]{500,}={0,2}''']
paths = ['''(?i).*\.ya?ml$''']
