// Code generated by protoc-gen-go. DO NOT EDIT.
// source: launcher.proto

package kolide_agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AGENT is added as a new log type, for adding new
// logging capabilities from kolide/agent
type LogCollection_LogType int32

const (
	LogCollection_RESULT LogCollection_LogType = 0
	LogCollection_STATUS LogCollection_LogType = 1
	LogCollection_AGENT  LogCollection_LogType = 2
)

var LogCollection_LogType_name = map[int32]string{
	0: "RESULT",
	1: "STATUS",
	2: "AGENT",
}
var LogCollection_LogType_value = map[string]int32{
	"RESULT": 0,
	"STATUS": 1,
	"AGENT":  2,
}

func (x LogCollection_LogType) String() string {
	return proto.EnumName(LogCollection_LogType_name, int32(x))
}
func (LogCollection_LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{5, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}
var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{8, 0}
}

type AgentApiRequest struct {
	NodeKey              string   `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentApiRequest) Reset()         { *m = AgentApiRequest{} }
func (m *AgentApiRequest) String() string { return proto.CompactTextString(m) }
func (*AgentApiRequest) ProtoMessage()    {}
func (*AgentApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{0}
}
func (m *AgentApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentApiRequest.Unmarshal(m, b)
}
func (m *AgentApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentApiRequest.Marshal(b, m, deterministic)
}
func (dst *AgentApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentApiRequest.Merge(dst, src)
}
func (m *AgentApiRequest) XXX_Size() int {
	return xxx_messageInfo_AgentApiRequest.Size(m)
}
func (m *AgentApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentApiRequest proto.InternalMessageInfo

func (m *AgentApiRequest) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

type AgentApiResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,3,opt,name=node_invalid,json=nodeInvalid" json:"node_invalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentApiResponse) Reset()         { *m = AgentApiResponse{} }
func (m *AgentApiResponse) String() string { return proto.CompactTextString(m) }
func (*AgentApiResponse) ProtoMessage()    {}
func (*AgentApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{1}
}
func (m *AgentApiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentApiResponse.Unmarshal(m, b)
}
func (m *AgentApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentApiResponse.Marshal(b, m, deterministic)
}
func (dst *AgentApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentApiResponse.Merge(dst, src)
}
func (m *AgentApiResponse) XXX_Size() int {
	return xxx_messageInfo_AgentApiResponse.Size(m)
}
func (m *AgentApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentApiResponse proto.InternalMessageInfo

func (m *AgentApiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AgentApiResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *AgentApiResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

type EnrollmentRequest struct {
	EnrollSecret         string   `protobuf:"bytes,1,opt,name=enroll_secret,json=enrollSecret" json:"enroll_secret,omitempty"`
	HostIdentifier       string   `protobuf:"bytes,2,opt,name=host_identifier,json=hostIdentifier" json:"host_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentRequest) Reset()         { *m = EnrollmentRequest{} }
func (m *EnrollmentRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollmentRequest) ProtoMessage()    {}
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{2}
}
func (m *EnrollmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentRequest.Unmarshal(m, b)
}
func (m *EnrollmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentRequest.Marshal(b, m, deterministic)
}
func (dst *EnrollmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentRequest.Merge(dst, src)
}
func (m *EnrollmentRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollmentRequest.Size(m)
}
func (m *EnrollmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentRequest proto.InternalMessageInfo

func (m *EnrollmentRequest) GetEnrollSecret() string {
	if m != nil {
		return m.EnrollSecret
	}
	return ""
}

func (m *EnrollmentRequest) GetHostIdentifier() string {
	if m != nil {
		return m.HostIdentifier
	}
	return ""
}

type EnrollmentResponse struct {
	NodeKey              string   `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid" json:"node_invalid,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollmentResponse) Reset()         { *m = EnrollmentResponse{} }
func (m *EnrollmentResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollmentResponse) ProtoMessage()    {}
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{3}
}
func (m *EnrollmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollmentResponse.Unmarshal(m, b)
}
func (m *EnrollmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollmentResponse.Marshal(b, m, deterministic)
}
func (dst *EnrollmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollmentResponse.Merge(dst, src)
}
func (m *EnrollmentResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollmentResponse.Size(m)
}
func (m *EnrollmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollmentResponse proto.InternalMessageInfo

func (m *EnrollmentResponse) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *EnrollmentResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *EnrollmentResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

// kolide/cloud will be generating well-structured json already, so forward
// it along instead of de/re/de-serializing it as a protobuf too
// this might make sense to convert to full proto later
type ConfigResponse struct {
	ConfigJsonBlob       string   `protobuf:"bytes,1,opt,name=config_json_blob,json=configJsonBlob" json:"config_json_blob,omitempty"`
	NodeInvalid          bool     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid" json:"node_invalid,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{4}
}
func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(dst, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetConfigJsonBlob() string {
	if m != nil {
		return m.ConfigJsonBlob
	}
	return ""
}

func (m *ConfigResponse) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *ConfigResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type LogCollection struct {
	NodeKey              string                `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`
	LogType              LogCollection_LogType `protobuf:"varint,2,opt,name=log_type,json=logType,enum=kolide.agent.LogCollection_LogType" json:"log_type,omitempty"`
	Logs                 []*LogCollection_Log  `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	ErrorCode            string                `protobuf:"bytes,4,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LogCollection) Reset()         { *m = LogCollection{} }
func (m *LogCollection) String() string { return proto.CompactTextString(m) }
func (*LogCollection) ProtoMessage()    {}
func (*LogCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{5}
}
func (m *LogCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCollection.Unmarshal(m, b)
}
func (m *LogCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCollection.Marshal(b, m, deterministic)
}
func (dst *LogCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCollection.Merge(dst, src)
}
func (m *LogCollection) XXX_Size() int {
	return xxx_messageInfo_LogCollection.Size(m)
}
func (m *LogCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCollection.DiscardUnknown(m)
}

var xxx_messageInfo_LogCollection proto.InternalMessageInfo

func (m *LogCollection) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *LogCollection) GetLogType() LogCollection_LogType {
	if m != nil {
		return m.LogType
	}
	return LogCollection_RESULT
}

func (m *LogCollection) GetLogs() []*LogCollection_Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type LogCollection_Log struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCollection_Log) Reset()         { *m = LogCollection_Log{} }
func (m *LogCollection_Log) String() string { return proto.CompactTextString(m) }
func (*LogCollection_Log) ProtoMessage()    {}
func (*LogCollection_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{5, 0}
}
func (m *LogCollection_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCollection_Log.Unmarshal(m, b)
}
func (m *LogCollection_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCollection_Log.Marshal(b, m, deterministic)
}
func (dst *LogCollection_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCollection_Log.Merge(dst, src)
}
func (m *LogCollection_Log) XXX_Size() int {
	return xxx_messageInfo_LogCollection_Log.Size(m)
}
func (m *LogCollection_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCollection_Log.DiscardUnknown(m)
}

var xxx_messageInfo_LogCollection_Log proto.InternalMessageInfo

func (m *LogCollection_Log) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// a query collection contains many queries
type QueryCollection struct {
	Queries              []*QueryCollection_Query `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	NodeInvalid          bool                     `protobuf:"varint,2,opt,name=node_invalid,json=nodeInvalid" json:"node_invalid,omitempty"`
	ErrorCode            string                   `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QueryCollection) Reset()         { *m = QueryCollection{} }
func (m *QueryCollection) String() string { return proto.CompactTextString(m) }
func (*QueryCollection) ProtoMessage()    {}
func (*QueryCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{6}
}
func (m *QueryCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCollection.Unmarshal(m, b)
}
func (m *QueryCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCollection.Marshal(b, m, deterministic)
}
func (dst *QueryCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollection.Merge(dst, src)
}
func (m *QueryCollection) XXX_Size() int {
	return xxx_messageInfo_QueryCollection.Size(m)
}
func (m *QueryCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollection.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollection proto.InternalMessageInfo

func (m *QueryCollection) GetQueries() []*QueryCollection_Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *QueryCollection) GetNodeInvalid() bool {
	if m != nil {
		return m.NodeInvalid
	}
	return false
}

func (m *QueryCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type QueryCollection_Query struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCollection_Query) Reset()         { *m = QueryCollection_Query{} }
func (m *QueryCollection_Query) String() string { return proto.CompactTextString(m) }
func (*QueryCollection_Query) ProtoMessage()    {}
func (*QueryCollection_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{6, 0}
}
func (m *QueryCollection_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCollection_Query.Unmarshal(m, b)
}
func (m *QueryCollection_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCollection_Query.Marshal(b, m, deterministic)
}
func (dst *QueryCollection_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollection_Query.Merge(dst, src)
}
func (m *QueryCollection_Query) XXX_Size() int {
	return xxx_messageInfo_QueryCollection_Query.Size(m)
}
func (m *QueryCollection_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollection_Query.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollection_Query proto.InternalMessageInfo

func (m *QueryCollection_Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryCollection_Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

// a result collection contains many results
type ResultCollection struct {
	NodeKey              string                     `protobuf:"bytes,1,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`
	Results              []*ResultCollection_Result `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	ErrorCode            string                     `protobuf:"bytes,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ResultCollection) Reset()         { *m = ResultCollection{} }
func (m *ResultCollection) String() string { return proto.CompactTextString(m) }
func (*ResultCollection) ProtoMessage()    {}
func (*ResultCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{7}
}
func (m *ResultCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection.Unmarshal(m, b)
}
func (m *ResultCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection.Marshal(b, m, deterministic)
}
func (dst *ResultCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection.Merge(dst, src)
}
func (m *ResultCollection) XXX_Size() int {
	return xxx_messageInfo_ResultCollection.Size(m)
}
func (m *ResultCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection proto.InternalMessageInfo

func (m *ResultCollection) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *ResultCollection) GetResults() []*ResultCollection_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ResultCollection) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

// status is moved here instead of appearing as a map of id[status]
// on the ResultCollection, as it does in the osq docs
type ResultCollection_Result struct {
	Id                   string                               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Rows                 []*ResultCollection_Result_ResultRow `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	Status               int32                                `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ResultCollection_Result) Reset()         { *m = ResultCollection_Result{} }
func (m *ResultCollection_Result) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result) ProtoMessage()    {}
func (*ResultCollection_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{7, 0}
}
func (m *ResultCollection_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result.Unmarshal(m, b)
}
func (m *ResultCollection_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result.Marshal(b, m, deterministic)
}
func (dst *ResultCollection_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result.Merge(dst, src)
}
func (m *ResultCollection_Result) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result.Size(m)
}
func (m *ResultCollection_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result proto.InternalMessageInfo

func (m *ResultCollection_Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResultCollection_Result) GetRows() []*ResultCollection_Result_ResultRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ResultCollection_Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ResultCollection_Result_ResultRow struct {
	Columns              []*ResultCollection_Result_ResultRow_Column `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ResultCollection_Result_ResultRow) Reset()         { *m = ResultCollection_Result_ResultRow{} }
func (m *ResultCollection_Result_ResultRow) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result_ResultRow) ProtoMessage()    {}
func (*ResultCollection_Result_ResultRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{7, 0, 0}
}
func (m *ResultCollection_Result_ResultRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Unmarshal(m, b)
}
func (m *ResultCollection_Result_ResultRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Marshal(b, m, deterministic)
}
func (dst *ResultCollection_Result_ResultRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result_ResultRow.Merge(dst, src)
}
func (m *ResultCollection_Result_ResultRow) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result_ResultRow.Size(m)
}
func (m *ResultCollection_Result_ResultRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result_ResultRow.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result_ResultRow proto.InternalMessageInfo

func (m *ResultCollection_Result_ResultRow) GetColumns() []*ResultCollection_Result_ResultRow_Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ResultCollection_Result_ResultRow_Column struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultCollection_Result_ResultRow_Column) Reset() {
	*m = ResultCollection_Result_ResultRow_Column{}
}
func (m *ResultCollection_Result_ResultRow_Column) String() string { return proto.CompactTextString(m) }
func (*ResultCollection_Result_ResultRow_Column) ProtoMessage()    {}
func (*ResultCollection_Result_ResultRow_Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{7, 0, 0, 0}
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Unmarshal(m, b)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Marshal(b, m, deterministic)
}
func (dst *ResultCollection_Result_ResultRow_Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Merge(dst, src)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_Size() int {
	return xxx_messageInfo_ResultCollection_Result_ResultRow_Column.Size(m)
}
func (m *ResultCollection_Result_ResultRow_Column) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultCollection_Result_ResultRow_Column.DiscardUnknown(m)
}

var xxx_messageInfo_ResultCollection_Result_ResultRow_Column proto.InternalMessageInfo

func (m *ResultCollection_Result_ResultRow_Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResultCollection_Result_ResultRow_Column) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,enum=kolide.agent.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_launcher_c35b30c2af6140f6, []int{8}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(dst, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterType((*AgentApiRequest)(nil), "kolide.agent.AgentApiRequest")
	proto.RegisterType((*AgentApiResponse)(nil), "kolide.agent.AgentApiResponse")
	proto.RegisterType((*EnrollmentRequest)(nil), "kolide.agent.EnrollmentRequest")
	proto.RegisterType((*EnrollmentResponse)(nil), "kolide.agent.EnrollmentResponse")
	proto.RegisterType((*ConfigResponse)(nil), "kolide.agent.ConfigResponse")
	proto.RegisterType((*LogCollection)(nil), "kolide.agent.LogCollection")
	proto.RegisterType((*LogCollection_Log)(nil), "kolide.agent.LogCollection.Log")
	proto.RegisterType((*QueryCollection)(nil), "kolide.agent.QueryCollection")
	proto.RegisterType((*QueryCollection_Query)(nil), "kolide.agent.QueryCollection.Query")
	proto.RegisterType((*ResultCollection)(nil), "kolide.agent.ResultCollection")
	proto.RegisterType((*ResultCollection_Result)(nil), "kolide.agent.ResultCollection.Result")
	proto.RegisterType((*ResultCollection_Result_ResultRow)(nil), "kolide.agent.ResultCollection.Result.ResultRow")
	proto.RegisterType((*ResultCollection_Result_ResultRow_Column)(nil), "kolide.agent.ResultCollection.Result.ResultRow.Column")
	proto.RegisterType((*HealthCheckResponse)(nil), "kolide.agent.HealthCheckResponse")
	proto.RegisterEnum("kolide.agent.LogCollection_LogType", LogCollection_LogType_name, LogCollection_LogType_value)
	proto.RegisterEnum("kolide.agent.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	// Attempt to enroll a host with kolide/cloud
	RequestEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	// request an updated configuration from kolide/cloud
	// a generic request object is sent
	RequestConfig(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// request/pull Dist queries from kolide/cloud
	// a generic request object is sent
	RequestQueries(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*QueryCollection, error)
	// publish logs from osqueryd to kolide/cloud
	// a generic response object is returned
	PublishLogs(ctx context.Context, in *LogCollection, opts ...grpc.CallOption) (*AgentApiResponse, error)
	// publish results from Dist queries to kolide/cloud
	// a generic response object is returned
	PublishResults(ctx context.Context, in *ResultCollection, opts ...grpc.CallOption) (*AgentApiResponse, error)
	// check the health of the GRPC server
	// a value indicating healthiness is returned
	// if you don't hear from this endpoint assume the worst
	CheckHealth(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) RequestEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	out := new(EnrollmentResponse)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/RequestEnrollment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RequestConfig(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/RequestConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RequestQueries(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*QueryCollection, error) {
	out := new(QueryCollection)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/RequestQueries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PublishLogs(ctx context.Context, in *LogCollection, opts ...grpc.CallOption) (*AgentApiResponse, error) {
	out := new(AgentApiResponse)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/PublishLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PublishResults(ctx context.Context, in *ResultCollection, opts ...grpc.CallOption) (*AgentApiResponse, error) {
	out := new(AgentApiResponse)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/PublishResults", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CheckHealth(ctx context.Context, in *AgentApiRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/kolide.agent.Api/CheckHealth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	// Attempt to enroll a host with kolide/cloud
	RequestEnrollment(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error)
	// request an updated configuration from kolide/cloud
	// a generic request object is sent
	RequestConfig(context.Context, *AgentApiRequest) (*ConfigResponse, error)
	// request/pull Dist queries from kolide/cloud
	// a generic request object is sent
	RequestQueries(context.Context, *AgentApiRequest) (*QueryCollection, error)
	// publish logs from osqueryd to kolide/cloud
	// a generic response object is returned
	PublishLogs(context.Context, *LogCollection) (*AgentApiResponse, error)
	// publish results from Dist queries to kolide/cloud
	// a generic response object is returned
	PublishResults(context.Context, *ResultCollection) (*AgentApiResponse, error)
	// check the health of the GRPC server
	// a value indicating healthiness is returned
	// if you don't hear from this endpoint assume the worst
	CheckHealth(context.Context, *AgentApiRequest) (*HealthCheckResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_RequestEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RequestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestConfig(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RequestQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RequestQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/RequestQueries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RequestQueries(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PublishLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/PublishLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishLogs(ctx, req.(*LogCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PublishResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/PublishResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishResults(ctx, req.(*ResultCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kolide.agent.Api/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CheckHealth(ctx, req.(*AgentApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kolide.agent.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestEnrollment",
			Handler:    _Api_RequestEnrollment_Handler,
		},
		{
			MethodName: "RequestConfig",
			Handler:    _Api_RequestConfig_Handler,
		},
		{
			MethodName: "RequestQueries",
			Handler:    _Api_RequestQueries_Handler,
		},
		{
			MethodName: "PublishLogs",
			Handler:    _Api_PublishLogs_Handler,
		},
		{
			MethodName: "PublishResults",
			Handler:    _Api_PublishResults_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _Api_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launcher.proto",
}

func init() { proto.RegisterFile("launcher.proto", fileDescriptor_launcher_c35b30c2af6140f6) }

var fileDescriptor_launcher_c35b30c2af6140f6 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x41, 0x6f, 0xeb, 0x44,
	0x10, 0x8e, 0xed, 0x24, 0x6e, 0x26, 0x8d, 0xe3, 0xb7, 0x20, 0x94, 0x17, 0xe8, 0x23, 0xcf, 0x4f,
	0x88, 0x1c, 0x1e, 0x41, 0x4a, 0x25, 0x0e, 0x48, 0x80, 0x42, 0x14, 0x95, 0xd2, 0x28, 0x6d, 0x9d,
	0x14, 0xb8, 0x59, 0x4e, 0xbc, 0x75, 0x4c, 0x37, 0xbb, 0xa9, 0xd7, 0x6e, 0x15, 0x89, 0x3b, 0xe2,
	0xc8, 0x11, 0xfe, 0x0d, 0x7f, 0x8a, 0x33, 0xf2, 0x7a, 0x9d, 0x36, 0x0e, 0x4d, 0x8a, 0x78, 0xb7,
	0x9d, 0xcf, 0x33, 0xf3, 0xcd, 0xb7, 0x3b, 0x33, 0x09, 0x18, 0xc4, 0x8d, 0xe9, 0x6c, 0x8e, 0xc3,
	0xce, 0x32, 0x64, 0x11, 0x43, 0x87, 0x37, 0x8c, 0x04, 0x1e, 0xee, 0xb8, 0x3e, 0xa6, 0x91, 0xf5,
	0x16, 0xea, 0xbd, 0xe4, 0xd0, 0x5b, 0x06, 0x36, 0xbe, 0x8d, 0x31, 0x8f, 0xd0, 0x4b, 0x38, 0xa0,
	0xcc, 0xc3, 0xce, 0x0d, 0x5e, 0x35, 0x94, 0x96, 0xd2, 0xae, 0xd8, 0x7a, 0x62, 0x9f, 0xe1, 0x95,
	0x45, 0xc1, 0x7c, 0xf0, 0xe6, 0x4b, 0x46, 0x39, 0x46, 0x0d, 0xd0, 0x17, 0x98, 0x73, 0xd7, 0xc7,
	0x99, 0xb7, 0x34, 0xd1, 0x11, 0x00, 0x0e, 0x43, 0x16, 0x3a, 0x33, 0xe6, 0xe1, 0x86, 0x2a, 0x3e,
	0x56, 0x04, 0xd2, 0x67, 0x1e, 0x46, 0xaf, 0xe1, 0x50, 0xf0, 0x04, 0xf4, 0xce, 0x25, 0x81, 0xd7,
	0xd0, 0x5a, 0x4a, 0xfb, 0xc0, 0xae, 0x26, 0xd8, 0x69, 0x0a, 0x59, 0x2e, 0xbc, 0x18, 0xd0, 0x90,
	0x11, 0xb2, 0xc0, 0x34, 0xca, 0xea, 0x7b, 0x03, 0x35, 0x2c, 0x40, 0x87, 0xe3, 0x59, 0x88, 0x23,
	0x49, 0x7b, 0x98, 0x82, 0x63, 0x81, 0xa1, 0x4f, 0xa1, 0x3e, 0x67, 0x3c, 0x72, 0x02, 0x0f, 0xd3,
	0x28, 0xb8, 0x0e, 0x70, 0x28, 0x0b, 0x30, 0x12, 0xf8, 0x74, 0x8d, 0x5a, 0xb7, 0x80, 0x1e, 0x53,
	0x48, 0x51, 0x4f, 0xdf, 0xc1, 0x56, 0xd9, 0xea, 0x56, 0xd9, 0x39, 0xe1, 0x5a, 0x4e, 0xb8, 0xf5,
	0x0b, 0x18, 0x7d, 0x46, 0xaf, 0x03, 0x7f, 0x4d, 0xd7, 0x06, 0x73, 0x26, 0x10, 0xe7, 0x67, 0xce,
	0xa8, 0x33, 0x25, 0x6c, 0x2a, 0x69, 0x8d, 0x14, 0xff, 0x9e, 0x33, 0xfa, 0x2d, 0x61, 0xd3, 0x77,
	0xc0, 0xfe, 0xab, 0x0a, 0xb5, 0x21, 0xf3, 0xfb, 0x8c, 0x10, 0x3c, 0x8b, 0x02, 0x46, 0x77, 0x89,
	0xfd, 0x1a, 0x0e, 0x08, 0xf3, 0x9d, 0x68, 0xb5, 0x4c, 0x1f, 0xd0, 0xe8, 0xbe, 0xe9, 0x3c, 0xee,
	0x9f, 0xce, 0x46, 0xa6, 0xc4, 0x9a, 0xac, 0x96, 0xd8, 0xd6, 0x49, 0x7a, 0x40, 0xc7, 0x50, 0x24,
	0xcc, 0xe7, 0x0d, 0xad, 0xa5, 0xb5, 0xab, 0xdd, 0x8f, 0xf7, 0xc4, 0xda, 0xc2, 0x39, 0x27, 0xa0,
	0x98, 0x13, 0xd0, 0x7c, 0x09, 0xda, 0x90, 0xf9, 0x08, 0x41, 0xd1, 0x73, 0x23, 0x57, 0x56, 0x2c,
	0xce, 0xd6, 0x5b, 0xd0, 0x65, 0x09, 0x08, 0xa0, 0x6c, 0x0f, 0xc6, 0x57, 0xc3, 0x89, 0x59, 0x48,
	0xce, 0xe3, 0x49, 0x6f, 0x72, 0x35, 0x36, 0x15, 0x54, 0x81, 0x52, 0xef, 0x64, 0x30, 0x9a, 0x98,
	0xaa, 0xf5, 0x97, 0x02, 0xf5, 0xcb, 0x18, 0x87, 0xab, 0x47, 0x77, 0xf1, 0x15, 0xe8, 0xb7, 0x31,
	0x0e, 0x03, 0xcc, 0x1b, 0x8a, 0xa8, 0x39, 0xa7, 0x37, 0xe7, 0x9f, 0xda, 0x76, 0x16, 0xf3, 0xff,
	0x9f, 0xa7, 0xf9, 0x19, 0x94, 0x44, 0x4e, 0x64, 0x80, 0x1a, 0x78, 0x52, 0x9d, 0x1a, 0x78, 0xe8,
	0x7d, 0x28, 0x25, 0x2c, 0x2b, 0xd9, 0xc7, 0xa9, 0x61, 0xfd, 0xa1, 0x81, 0x69, 0x63, 0x1e, 0x93,
	0xe8, 0x79, 0x0f, 0xfa, 0x0d, 0xe8, 0xa1, 0x70, 0xe7, 0x0d, 0x55, 0xe8, 0xfb, 0x64, 0x53, 0x5f,
	0x3e, 0x97, 0x04, 0xec, 0x2c, 0x6a, 0x5f, 0xf9, 0xbf, 0xa9, 0x50, 0x4e, 0x43, 0xb6, 0x04, 0xf4,
	0xa1, 0x18, 0xb2, 0xfb, 0x8c, 0xf7, 0xf3, 0x67, 0xf1, 0x66, 0xf4, 0xec, 0xde, 0x16, 0xc1, 0xe8,
	0x03, 0x28, 0xf3, 0xc8, 0x8d, 0x62, 0x2e, 0xa8, 0x4b, 0xb6, 0xb4, 0x9a, 0xbf, 0x2b, 0x50, 0x59,
	0xfb, 0xa2, 0x0b, 0xd0, 0x67, 0x8c, 0xc4, 0x0b, 0x9a, 0xbd, 0xe2, 0x17, 0xff, 0x91, 0xad, 0xd3,
	0x17, 0xe1, 0x76, 0x96, 0xa6, 0xd9, 0x85, 0x72, 0x0a, 0x25, 0x7d, 0x47, 0xdd, 0x45, 0xb6, 0xec,
	0xc4, 0x39, 0x79, 0x9b, 0x3b, 0x97, 0xc4, 0xd9, 0x92, 0x4b, 0x0d, 0xeb, 0x4f, 0x05, 0xde, 0xfb,
	0x0e, 0xbb, 0x24, 0x9a, 0xf7, 0xe7, 0x78, 0x76, 0xb3, 0x9e, 0xf6, 0x93, 0xb5, 0x06, 0x45, 0x8c,
	0x54, 0xee, 0x2a, 0xfe, 0x25, 0xa4, 0x33, 0xc6, 0xe1, 0x5d, 0x40, 0xfd, 0xb1, 0x08, 0xcb, 0x44,
	0x5b, 0x5f, 0x42, 0x6d, 0xe3, 0x03, 0xaa, 0x82, 0x7e, 0x35, 0x3a, 0x1b, 0x9d, 0xff, 0x38, 0x32,
	0x0b, 0x89, 0x31, 0x1e, 0xd8, 0x3f, 0x9c, 0x8e, 0x4e, 0x4c, 0x05, 0xd5, 0xa1, 0x3a, 0x3a, 0x9f,
	0x38, 0x19, 0xa0, 0x76, 0xff, 0xd6, 0x40, 0xeb, 0x2d, 0x03, 0xf4, 0x13, 0xbc, 0x90, 0x8b, 0xf5,
	0x61, 0x0d, 0xa2, 0xdc, 0xa0, 0x6e, 0xed, 0xe0, 0x66, 0xeb, 0x69, 0x87, 0xb4, 0x62, 0xab, 0x80,
	0x46, 0x50, 0x93, 0xee, 0xe9, 0xb6, 0x43, 0x47, 0x9b, 0x41, 0xb9, 0xdf, 0x9d, 0xe6, 0x47, 0x9b,
	0x9f, 0x37, 0x57, 0xa4, 0x55, 0x40, 0x17, 0x60, 0x48, 0xd7, 0x4b, 0x39, 0x6d, 0x7b, 0x12, 0x1e,
	0xed, 0x1c, 0x5d, 0xab, 0x80, 0x86, 0x50, 0xbd, 0x88, 0xa7, 0x24, 0xe0, 0xf3, 0x61, 0xb2, 0x77,
	0x3e, 0xdc, 0xb1, 0x9e, 0x9a, 0xaf, 0x9e, 0xe2, 0x5a, 0xd7, 0x67, 0x83, 0x21, 0xb3, 0xd9, 0x72,
	0x56, 0x5e, 0xed, 0xee, 0xba, 0x67, 0xe4, 0xbc, 0x84, 0xaa, 0x68, 0x84, 0xb4, 0x27, 0xf6, 0x09,
	0x7e, 0xbd, 0xb7, 0x91, 0xac, 0xc2, 0xb4, 0x2c, 0xfe, 0x06, 0x1c, 0xff, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0x31, 0x65, 0x6b, 0x18, 0x08, 0x00, 0x00,
}
