#!/bin/bash

/bin/launchctl stop com.kolide.launcher

sleep 5

/bin/launchctl unload /Library/LaunchDaemons/com.kolide.launcher.plist
/bin/launchctl load /Library/LaunchDaemons/com.kolide.launcher.plist
