// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewActor creates a new instance of Actor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Actor {
	mock := &Actor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Actor is an autogenerated mock type for the actor type
type Actor struct {
	mock.Mock
}

type Actor_Expecter struct {
	mock *mock.Mock
}

func (_m *Actor) EXPECT() *Actor_Expecter {
	return &Actor_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type Actor
func (_mock *Actor) Do(data io.Reader) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Actor_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Actor_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - data io.Reader
func (_e *Actor_Expecter) Do(data interface{}) *Actor_Do_Call {
	return &Actor_Do_Call{Call: _e.mock.On("Do", data)}
}

func (_c *Actor_Do_Call) Run(run func(data io.Reader)) *Actor_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Actor_Do_Call) Return(err error) *Actor_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Actor_Do_Call) RunAndReturn(run func(data io.Reader) error) *Actor_Do_Call {
	_c.Call.Return(run)
	return _c
}
