@interface SUOSUShimController : NSObject {
    _Bool _didPostScanCompleteNotification;
    _Bool _scanInProgress;
    _Bool _isBackgroundScanInProgress;
    int _legacyBackgroundScanInitiatedNotifyToken;
    int _backgroundScanInitiatedNotifyToken;
    int _backgroundScanCompleteNotifyToken;
    int _clientScanNotifyToken;
    //NSObject<OS_dispatch_queue> *_operationQueue;
    //NSObject<OS_dispatch_queue> *_installNotifyQueue;
    //NSObject<OS_dispatch_source> *_inProgressUpdateTimerSource;
    //id <SUOSUClientDelegate> _delegate;
    //SUOSUClient *_client;
    //SUAppStoreUpdateController *_appStoreUpdateController;
    //SUOSUUpdateController *_updateController;
    //SUOSUNotificationManagerController *_notificationManager;
    //SUPowerAssertionManager *_powerAssertionManager;
    //SUOSUSpoofedUpdates *_spoofedUpdates;
    id _queuedForLaterUpdatesObserverToken;
    id _catalogURLObserverToken;
    NSArray *_availableUpdates;
    NSArray *_availableMajorUpdates;
    //SUOSUMajorProduct *_latestQualifyingMajorProduct;
    NSDate *_latestCatalogModifiedDate;
}

//@property (retain) NSObject<OS_dispatch_queue> *operationQueue;
//@property (retain) NSObject<OS_dispatch_queue> *installNotifyQueue;
//@property (retain) NSObject<OS_dispatch_source> *inProgressUpdateTimerSource;
//@property (retain) id <SUOSUClientDelegate> delegate;
//@property (weak) SUOSUClient *client;
//@property (retain, nonatomic) SUAppStoreUpdateController *appStoreUpdateController;
//@property (retain, nonatomic) SUOSUUpdateController *updateController;
//@property (retain, nonatomic) SUOSUNotificationManagerController *notificationManager;
//@property (retain) SUPowerAssertionManager *powerAssertionManager;
//@property (retain) SUOSUSpoofedUpdates *spoofedUpdates;
@property int legacyBackgroundScanInitiatedNotifyToken;
@property int backgroundScanInitiatedNotifyToken;
@property int backgroundScanCompleteNotifyToken;
@property int clientScanNotifyToken;
@property (retain) id queuedForLaterUpdatesObserverToken;
@property (retain) id catalogURLObserverToken;
@property _Bool didPostScanCompleteNotification;
@property (retain) NSArray *availableUpdates;
@property (readonly, nonatomic) NSArray *availableMobileSoftwareUpdates;
@property (retain) NSArray *availableMajorUpdates;
//@property (retain) SUOSUMajorProduct *latestQualifyingMajorProduct;
@property (retain, nonatomic) NSDate *latestCatalogModifiedDate;
@property (nonatomic) _Bool scanInProgress;
@property _Bool isBackgroundScanInProgress;
@property (readonly) _Bool isAutomaticallyCheckForUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyDownloadUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallMacOSUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallBackgroundSecurityImprovementsPreferenceEnabled;
@property (readonly) _Bool isAutomaticallyCheckForUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyDownloadUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallMacOSUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallBackgroundSecurityImprovementsPreferenceManaged;
@property (readonly) NSString *catalogURL;
@property (readonly) NSString *pallasAudience;
@property (readonly) NSDate *latestSuccessfulScanDate;
@property (readonly) _Bool deferredUpdatesExist;
@property (readonly) _Bool deferralEnabled;
@property (readonly) _Bool shouldShowCatalogSelector;

- (id)operationQueue;
- (id)notificationManager;
- (void)setOperationQueue:(id)queue;
- (void)setClient:(id)client;
- (void)start;
- (id)client;
- (id)delegate;
- (void)setDelegate:(id)delegate;
- (void)setNotificationManager:(id)manager;
- (_Bool)isSupervised;
- (id)updateController;
- (id)availableUpdates;
- (id)catalogURL;
- (_Bool)deferredUpdatesExist;
- (_Bool)setCatalogURL:(id)url;
- (id)_createProgress;
- (void)_promptAndQueueDownloadedUpdates:(id)updates withPostInstallAction:(unsigned long long)action options:(id)options;
- (_Bool)deferralEnabled;
- (_Bool)didPostScanCompleteNotification;
- (_Bool)isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceEnabled;
- (void)setInProgressUpdateTimerSource:(id)source;
- (id)_latestQualifyingMajorOSProduct;
- (_Bool)isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceManaged;
- (unsigned long long)__requestFreeSpace:(unsigned long long)space error:(id *)error;
- (id)_activeMobileSoftwareUpdateInForeground;
- (id)_appStoreUpdatesForProducts:(id)products;
- (_Bool)_authorizeForInstall;
- (_Bool)_authorizeForInstallMDMInitiated:(_Bool)mdminitiated;
- (id)_availableCriticalUpdates;
- (id)_availableUpdatesForProductKeys:(id)keys;
- (void)_cancelPowerAssertion;
- (_Bool)_checkPowerRequirementForUpdates:(id)updates foreground:(_Bool)foreground error:(id *)error;
- (id)_configDataProductsForAppStoreUpdates:(id)updates;
- (void)_getCatalogConfigurationInformationForCompletedScan:(_Bool)scan withScanError:(_Bool)error;
- (void)_handleCatalogURLChanged;
- (id)_handleDownloadError:(id)error forProducts:(id)products;
- (void)_handleForegroundSplatApply:(id)apply;
- (void)_handleNotifyingUpdatesChanged;
- (void)_handleQueuedUpdatesForLaterChanged;
- (void)_handleRestartCountdownCompletionForProducts:(id)products options:(id)options alreadyDownloadedAndPrepared:(_Bool)prepared error:(id)error;
- (void)_handleSuccessfullyCompletedScan;
- (void)_installConfigDataUpdateWithProductKeys:(id)keys;
- (id)_insufficientDiskSpaceErrorForProducts:(id)products spaceRequired:(unsigned long long)required underlyingError:(id)error;
- (_Bool)_lastKnownCatalogHostNameIsDefault;
- (id)_majorOSInstallerBundleIdentifierForAppStoreUpdate:(id)update;
- (id)_mobileSoftwareUpdatesForProducts:(id)products;
- (_Bool)_obtainLAContextWithProduct:(id)product options:(id)options error:(id *)error;
- (_Bool)_obtainLAContextWithWindow:(id)window options:(id)options product:(id)product error:(id *)error;
- (unsigned long long)_postInstallActionForUpdates:(id)updates;
- (_Bool)_prepareForInstallingUpdates:(id)updates isDoItLater:(_Bool)later scheduleUpdatesForLater:(_Bool)later mdmInitiated:(_Bool)initiated skipLicenseAgreement:(_Bool)agreement window:(id)window;
- (id)_productKeysForProducts:(id)products;
- (id)_productKeysInActiveForegroundTransactions;
- (_Bool)_promptAndSuspendMobileAssetIfNecessaryWithFreeSpaceRequired:(unsigned long long)required suspendedMobileAsset:(_Bool *)asset error:(id *)error;
- (void)_queueUpdatesForLater:(id)later withReason:(unsigned long long)reason mdmInitiated:(_Bool)initiated window:(id)window;
- (_Bool)_quitMustCloseApplicationsForUpdates:(id)updates isDoItLater:(_Bool)later;
- (_Bool)_reclaimDiskSpaceIfNecssaryWithBytesRequired:(unsigned long long)required bytesReclaimed:(unsigned long long *)reclaimed error:(id *)error;
- (void)_refreshAllAvailableUpdatesAndNotifyDelegate;
- (void)_registerForBackgroundScanInitiatedNotification:(id)notification outToken:(int *)token;
- (void)_registerForScanCompletionNotification:(id)notification outToken:(int *)token;
- (void)_registerForStateChangeNotifications;
- (unsigned long long)_requestAndWaitForResponseToUserAction:(unsigned long long)action details:(id)details;
- (void)_setIdleSleepPowerAssertion;
- (void)_setMaintenancePowerAssertion;
- (_Bool)_shouldRescan;
- (_Bool)_showFirmwareWarningsForUpdates:(id)updates;
- (_Bool)_showLicenseAgreementsForUpdates:(id)updates skipSLA:(_Bool)sla;
- (void)_startInstallForNonExternalUpdates:(id)updates downloadRequired:(_Bool)required preparationRequired:(_Bool)required postInstallAction:(unsigned long long)action withOptions:(id)options;
- (void)_startInstallingUpdates:(id)updates withWindow:(id)window withOptions:(id)options;
- (void)_startInstallingUpdatesRequiringNoPostInstallAction:(id)action inForeground:(_Bool)foreground nowIsLater:(_Bool)later mdmInitiated:(_Bool)initiated;
- (void)_startInstallingUpdatesRequiringNoPostInstallAction:(id)action inForeground:(_Bool)foreground nowIsLater:(_Bool)later mdmInitiated:(_Bool)initiated completion:(id /* block */)completion;
- (void)_startRestartCountdownOperationForUpdates:(id)updates options:(id)options downloadedAndPrepared:(_Bool)prepared;
- (void)_startShowingProgressForExternalUpdate:(id)update mdmInitiated:(_Bool)initiated successCompletion:(id /* block */)completion;
- (void)_startShowingProgressForMobileSoftwareUpdate:(id)update mdmInitiated:(_Bool)initiated successCompletion:(id /* block */)completion;
- (void)_startShowingProgressForProductKeys:(id)keys mdmInitiated:(_Bool)initiated;
- (void)_startShowingProgressForUpdates:(id)updates mdmInitiated:(_Bool)initiated cancellationHandler:(id /* block */)handler successCompletion:(id /* block */)completion;
- (void)_startUpAndDetermineCurrentState;
- (void)_trySimulateSuspendMobileAsset;
- (void)_updateLatestAvailableMajorProductState;
- (void)_updateProgress:(id)progress forProducts:(id)products percentComplete:(float)complete status:(id)status;
- (id)_userVisibleProductsForAppStoreUpdates:(id)updates;
- (id)appStoreUpdateController;
- (_Bool)authorizeForModifyingPreferences;
- (void)authorizeForModifyingPreferencesWithCompletion:(id /* block */)completion;
- (id)availableMajorUpdates;
- (id)availableMobileSoftwareUpdates;
- (_Bool)availableUpdatesDownloaded;
- (int)backgroundScanCompleteNotifyToken;
- (int)backgroundScanInitiatedNotifyToken;
- (void)cacheDeletePurgeableSpaceWithCompletionHandler:(id /* block */)handler;
- (_Bool)cancelUpdatesQueuedForInstallLater;
- (id)catalogURLObserverToken;
- (void)clearProductKeysToAutoInstall;
- (int)clientScanNotifyToken;
- (unsigned long long)diskSpaceRequiredForProducts:(id)products;
- (id)enforcedDDMDeclaration;
- (id)enforcedDDMPastDuePaddedDeclarationDate;
- (id)inProgressUpdateTimerSource;
- (id)initWithClient:(id)client delegate:(id)delegate;
- (void)installConfigDataUpdates;
- (id)installNotifyQueue;
- (_Bool)isAutomaticallyCheckForUpdatesPreferenceEnabled;
- (_Bool)isAutomaticallyCheckForUpdatesPreferenceManaged;
- (_Bool)isAutomaticallyDownloadUpdatesPreferenceEnabled;
- (_Bool)isAutomaticallyDownloadUpdatesPreferenceManaged;
- (_Bool)isAutomaticallyInstallBackgroundSecurityImprovementsPreferenceEnabled;
- (_Bool)isAutomaticallyInstallBackgroundSecurityImprovementsPreferenceManaged;
- (_Bool)isAutomaticallyInstallMacOSUpdatesPreferenceEnabled;
- (_Bool)isAutomaticallyInstallMacOSUpdatesPreferenceManaged;
- (_Bool)isBackgroundScanInProgress;
- (_Bool)isDDMManagedProduct:(id)product;
- (id)latestCatalogModifiedDate;
- (id)latestQualifyingMajorProduct;
- (id)latestSuccessfulScanDate;
- (int)legacyBackgroundScanInitiatedNotifyToken;
- (_Bool)managedInstallLaterUpdatesScheduled;
- (_Bool)observeForegroundInstallInProgress;
- (_Bool)osUpdateDownloadedAndPreparedForProduct:(id)product;
- (id)pallasAudience;
- (_Bool)pallasAudienceIsDefault;
- (unsigned long long)postInstallActionForUpdates:(id)updates;
- (id)powerAssertionManager;
- (void)queueUpdatesForLater:(id)later withReason:(unsigned long long)reason window:(id)window;
- (id)queuedForLaterUpdates;
- (id)queuedForLaterUpdatesObserverToken;
- (_Bool)resetToProductionCatalog;
- (void)resetToProductionCatalogWithCompletion:(id /* block */)completion;
- (_Bool)scanInProgress;
- (void)setAppStoreUpdateController:(id)controller;
//- (void)setAvailableMajorUpdates:(id)updates;
//- (void)setAvailableUpdates:(id)updates;
- (void)setBackgroundScanCompleteNotifyToken:(int)token;
- (void)setBackgroundScanInitiatedNotifyToken:(int)token;
- (void)setCatalogURLObserverToken:(id)token;
- (void)setClientScanNotifyToken:(int)token;
- (void)setDidPostScanCompleteNotification:(_Bool)notification;
- (void)setInstallNotifyQueue:(id)queue;
- (void)setIsAutomaticallyDownloadUpdatesPreferenceEnabled:(_Bool)enabled;
- (void)setIsAutomaticallyInstallBackgroundSecurityImprovementsPreferenceEnabled:(_Bool)enabled;
- (void)setIsAutomaticallyInstallMacOSUpdatesPreferenceEnabled:(_Bool)enabled;
- (void)setIsAutomaticallyInstallSecurityAndConfigUpdatesPreferenceEnabled:(_Bool)enabled;
- (void)setIsBackgroundScanInProgress:(_Bool)progress;
//- (void)setLatestCatalogModifiedDate:(id)date;
- (void)setLatestQualifyingMajorProduct:(id)product;
- (void)setLegacyBackgroundScanInitiatedNotifyToken:(int)token;
- (void)setPowerAssertionManager:(id)manager;
- (void)setQueuedForLaterUpdatesObserverToken:(id)token;
- (void)setScanInProgress:(_Bool)progress;
- (void)setSpoofedUpdates:(id)updates;
- (void)setUpdateController:(id)controller;
- (_Bool)shouldShowCatalogSelector;
- (id)spoofedUpdates;
- (void)startInstallingMajorOSVersion:(id)osversion orWithMajorOSBundleIdentifier:(id)identifier majorOSVariant:(id)osvariant shouldOpenIA:(_Bool)ia inForeground:(_Bool)foreground isMDMInitiated:(_Bool)mdminitiated;
- (void)startInstallingMajorOSVersion:(id)osversion orWithMajorOSBundleIdentifier:(id)identifier majorOSVariant:(id)osvariant shouldOpenIA:(_Bool)ia inForeground:(_Bool)foreground isMDMInitiated:(_Bool)mdminitiated fromAvailableMajorUpdates:(id)updates;
- (void)startInstallingUpdates:(id)updates isDoItLater:(_Bool)later inForeground:(_Bool)foreground mdmInitiated:(_Bool)initiated;
- (void)startInstallingUpdates:(id)updates window:(id)window withOptions:(id)options;
- (void)startInstallingUpdates:(id)updates withOptions:(id)options;
- (void)startScanningForLegacyUpdatesOnlyEvenIfUnchanged:(_Bool)unchanged background:(_Bool)background withCompletionHandler:(id /* block */)handler;
- (void)startScanningForUpdatesEvenIfUnchanged:(_Bool)unchanged background:(_Bool)background withCompletionHandler:(id /* block */)handler;
- (void)startScanningForUpdatesEvenIfUnchanged:(_Bool)unchanged withCompletionHandler:(id /* block */)handler;

@end