//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.549, BuildCommit: 3da8ece356e0f31d6b3a8e7f419e446ace69898f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15, SDK: 15, Tool: ld (1115.7.3)
//    - LC_SOURCE_VERSION: 2038.1.1.0.0
//
#ifndef SUOSUClientProtocol_Protocol_h
#define SUOSUClientProtocol_Protocol_h

@class NSImage;

@protocol SUOSUClientProtocol <NSObject>

@required

@property (readonly) unsigned long long clientType;
@property (copy) id /* block */ progressCompletion;
@property (readonly) _Bool isAutomaticallyCheckForUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyDownloadUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallMacOSUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallAppUpdatesPreferenceEnabled;
@property _Bool isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceEnabled;
@property (readonly) _Bool isAutomaticallyCheckForUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyDownloadUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallMacOSUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallAppUpdatesPreferenceManaged;
@property (readonly) _Bool isAutomaticallyInstallSecurityAndConfigUpdatesPreferenceManaged;
@property (readonly) NSString *catalogURL;
@property (readonly) NSString *pallasAudience;
@property (readonly) NSImage *currentSystemImage;
@property (readonly) NSDate *latestSuccessfulScanDate;
@property (readonly) _Bool deferredUpdatesExist;
@property (readonly) _Bool deferralEnabled;
@property (readonly) _Bool shouldShowCatalogSelector;
@property (readonly) NSString *marketingNameString;
@property (readonly) NSString *systemVersionString;
@property (readonly) NSString *buildVersionString;

/* required instance methods */
- (id)init;
- (_Bool)isSupervised;
- (_Bool)authorizeForModifyingPreferences;
- (void)authorizeForModifyingPreferencesWithCompletion:(id /* block */)completion;
- (_Bool)availableUpdatesDownloaded;
- (_Bool)cancelUpdatesQueuedForLater;
- (unsigned long long)diskSpaceRequiredForProducts:(id)products;
- (id)enforcedDDMDeclaration;
- (id)enforcedDDMPastDuePaddedDeclarationDate;
- (id)initWithDelegate:(id)delegate type:(unsigned long long)type;
- (void)installConfigDataUpdates;
- (_Bool)isDDMManagedProduct:(id)product;
- (_Bool)managedInstallLaterUpdatesScheduled;
- (_Bool)observeForegroundInstallInProgress;
- (_Bool)osUpdateDownloadedAndPreparedForProduct:(id)product;
- (unsigned long long)postInstallActionForUpdates:(id)updates;
- (void)queueAllAutoUpdatesForLater;
- (void)queueAllUpdatesForLater;
- (void)queueUpdatesForLater:(id)later window:(id)window;
- (_Bool)resetToProductionCatalog;
- (void)resetToProductionCatalogWithCompletion:(id /* block */)completion;
- (void)startInstallingMDMUpdates:(id)mdmupdates isDoItLater:(_Bool)later inForeground:(_Bool)foreground;
- (void)startInstallingMajorOSVersion:(id)osversion orWithMajorOSBundleIdentifier:(id)identifier majorOSVariant:(id)osvariant shouldOpenIA:(_Bool)ia inForeground:(_Bool)foreground isMDMInitiated:(_Bool)mdminitiated;
- (void)startInstallingMajorOSVersion:(id)osversion orWithMajorOSBundleIdentifier:(id)identifier majorOSVariant:(id)osvariant shouldOpenIA:(_Bool)ia inForeground:(_Bool)foreground isMDMInitiated:(_Bool)mdminitiated fromAvailableMajorUpdates:(id)updates;
- (void)startInstallingUpdates:(id)updates;
- (void)startInstallingUpdates:(id)updates inForeground:(_Bool)foreground;
- (void)startInstallingUpdates:(id)updates isDoItLater:(_Bool)later inForeground:(_Bool)foreground;
- (void)startInstallingUpdates:(id)updates window:(id)window withOptions:(id)options;
- (void)startScanningForLegacyUpdatesEvenIfUnchanged:(_Bool)unchanged;
- (void)startScanningForUpdatesEvenIfUnchanged:(_Bool)unchanged;
- (void)startScanningForUpdatesEvenIfUnchanged:(_Bool)unchanged withCompletionHandler:(id /* block */)handler;

@optional

@end

#endif /* SUOSUClientProtocol_Protocol_h */
