// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewFlagValueOverride creates a new instance of FlagValueOverride. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagValueOverride(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagValueOverride {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FlagValueOverride{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FlagValueOverride is an autogenerated mock type for the FlagValueOverride type
type FlagValueOverride struct {
	mock.Mock
}

type FlagValueOverride_Expecter struct {
	mock *mock.Mock
}

func (_m *FlagValueOverride) EXPECT() *FlagValueOverride_Expecter {
	return &FlagValueOverride_Expecter{mock: &_m.Mock}
}

// Value provides a mock function for the type FlagValueOverride
func (_mock *FlagValueOverride) Value() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// FlagValueOverride_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type FlagValueOverride_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *FlagValueOverride_Expecter) Value() *FlagValueOverride_Value_Call {
	return &FlagValueOverride_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *FlagValueOverride_Value_Call) Run(run func()) *FlagValueOverride_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlagValueOverride_Value_Call) Return(anyMoqParam any) *FlagValueOverride_Value_Call {
	_c.Call.Return(anyMoqParam)
	return _c
}

func (_c *FlagValueOverride_Value_Call) RunAndReturn(run func() any) *FlagValueOverride_Value_Call {
	_c.Call.Return(run)
	return _c
}
