// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMessenger creates a new instance of Messenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Messenger {
	mock := &Messenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Messenger is an autogenerated mock type for the Messenger type
type Messenger struct {
	mock.Mock
}

type Messenger_Expecter struct {
	mock *mock.Mock
}

func (_m *Messenger) EXPECT() *Messenger_Expecter {
	return &Messenger_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type Messenger
func (_mock *Messenger) SendMessage(method string, params any) error {
	ret := _mock.Called(method, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(method, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Messenger_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Messenger_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - method string
//   - params any
func (_e *Messenger_Expecter) SendMessage(method interface{}, params interface{}) *Messenger_SendMessage_Call {
	return &Messenger_SendMessage_Call{Call: _e.mock.On("SendMessage", method, params)}
}

func (_c *Messenger_SendMessage_Call) Run(run func(method string, params any)) *Messenger_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Messenger_SendMessage_Call) Return(err error) *Messenger_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Messenger_SendMessage_Call) RunAndReturn(run func(method string, params any) error) *Messenger_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
