// Code generated by mockery v2.21.1. DO NOT EDIT.

package tuf

import mock "github.com/stretchr/testify/mock"

// mockLibrarian is an autogenerated mock type for the librarian type
type mockLibrarian struct {
	mock.Mock
}

// AddToLibrary provides a mock function with given fields: binary, targetFilename
func (_m *mockLibrarian) AddToLibrary(binary autoupdatableBinary, targetFilename string) error {
	ret := _m.Called(binary, targetFilename)

	var r0 error
	if rf, ok := ret.Get(0).(func(autoupdatableBinary, string) error); ok {
		r0 = rf(binary, targetFilename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AvailableInLibrary provides a mock function with given fields: binary, targetFilename
func (_m *mockLibrarian) AvailableInLibrary(binary autoupdatableBinary, targetFilename string) bool {
	ret := _m.Called(binary, targetFilename)

	var r0 bool
	if rf, ok := ret.Get(0).(func(autoupdatableBinary, string) bool); ok {
		r0 = rf(binary, targetFilename)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// TidyLibrary provides a mock function with given fields:
func (_m *mockLibrarian) TidyLibrary() {
	_m.Called()
}

type mockConstructorTestingTnewMockLibrarian interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLibrarian creates a new instance of mockLibrarian. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLibrarian(t mockConstructorTestingTnewMockLibrarian) *mockLibrarian {
	mock := &mockLibrarian{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
