steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--tag=gcr.io/kolide-public-containers/launcher-builder:1.10.1',
            '.'
        ]

images:
        - 'gcr.io/kolide-public-containers/launcher-builder:1.10.1'
