name: actionlint

# See https://github.com/rhysd/actionlint

on:
  pull_request:
    branches:
      - main
      - master
  merge_group:
    types: [checks_requested]


jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go 1.x
        uses: actions/setup-go@v7
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: false
      - name: install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
      - name: actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          actionlint -color
