name: reproducible

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: "*"
  pull_request:
    branches: "**"
  merge_group:
    types: [checks_requested]

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    outputs:
      sde: ${{ steps.time.outputs.sde }}
    steps:
      - name: Set time
        id: time
        run: |
          echo "sde=${SOURCE_DATE_EPOCH:-$(date +%s)}" >> "$GITHUB_OUTPUT"

  first_build:
    needs: setup
    name: build-1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need a full checkout for `git describe`

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./go.mod"
          check-latest: true
          cache: false
        id: go

      - id: go-cache-paths
        shell: bash
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

      - name: Go Build Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      - name: Set up zig
        uses: mlugg/setup-zig@v2

      - name: Build 1
        run: |
          make -j2 github-build SOURCE_DATE_EPOCH=${{ needs.setup.outputs.sde }}
          mv build build1
          ./build1/linux.amd64/launcher --version

      - name: Cache build output
        uses: actions/cache@v5
        with:
          path: ./build1
          key: ${{ github.run_id }}-reproducible-1
          enableCrossOsArchive: true

  second_build:
    needs: setup
    name: build-2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need a full checkout for `git describe`

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./go.mod"
          check-latest: true
          cache: false
        id: go

      - id: go-cache-paths
        shell: bash
        run: |
          echo "go-build=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

      - name: Go Build Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: make deps

      - name: Set up zig
        uses: mlugg/setup-zig@v2
      
      - name: Build 2
        run: |
          make -j2 github-build SOURCE_DATE_EPOCH=${{ needs.setup.outputs.sde }}
          mv build build2
          ./build2/linux.amd64/launcher --version

      - name: Cache build output
        uses: actions/cache@v5
        with:
          path: ./build2
          key: ${{ github.run_id }}-reproducible-2
          enableCrossOsArchive: true

  verify:
    needs: [first_build, second_build]
    name: verify
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: cache restore build 1 output
        uses: actions/cache/restore@v5
        with:
          path: ./build1
          key: ${{ github.run_id }}-reproducible-1
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: cache restore build 2 output
        uses: actions/cache/restore@v5
        with:
          path: ./build2
          key: ${{ github.run_id }}-reproducible-2
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Install diffoscope
        run: |
          sudo apt-get update
          sudo apt-get -y install diffoscope

      - name: Verify
        run: |
          VERSIONOUTPUT1=$(./build1/linux.amd64/launcher --version)
          VERSIONOUTPUT2=$(./build2/linux.amd64/launcher --version)
          if [ "$VERSIONOUTPUT1" = "$VERSIONOUTPUT2" ]; then
            echo "Version output matches"
          else
            echo "Version outputs differ: build 1: ${VERSIONOUTPUT1}: build 2: ${VERSIONOUTPUT2}"
            exit 1
          fi
          HASH1=$(sha256sum build1/linux.amd64/launcher | awk '{ print $1 }')
          HASH2=$(sha256sum build2/linux.amd64/launcher | awk '{ print $1 }')
          if [ "$HASH1" = "$HASH2" ]; then
            echo "Builds match"
          else
            echo "Builds differ: build 1: ${HASH1}: build 2: ${HASH2}"
            diffoscope ./build1/linux.amd64/launcher ./build2/linux.amd64/launcher
          fi
