// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto"

	"github.com/kolide/krypto/pkg/tpm"
	mock "github.com/stretchr/testify/mock"
)

// NewTpmSignerCreator creates a new instance of TpmSignerCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTpmSignerCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TpmSignerCreator {
	mock := &TpmSignerCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TpmSignerCreator is an autogenerated mock type for the tpmSignerCreator type
type TpmSignerCreator struct {
	mock.Mock
}

type TpmSignerCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *TpmSignerCreator) EXPECT() *TpmSignerCreator_Expecter {
	return &TpmSignerCreator_Expecter{mock: &_m.Mock}
}

// CreateKey provides a mock function for the type TpmSignerCreator
func (_mock *TpmSignerCreator) CreateKey(opts ...tpm.TpmSignerOption) ([]byte, []byte, error) {
	// tpm.TpmSignerOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(...tpm.TpmSignerOption) ([]byte, []byte, error)); ok {
		return returnFunc(opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(...tpm.TpmSignerOption) []byte); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...tpm.TpmSignerOption) []byte); ok {
		r1 = returnFunc(opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(...tpm.TpmSignerOption) error); ok {
		r2 = returnFunc(opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TpmSignerCreator_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type TpmSignerCreator_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - opts ...tpm.TpmSignerOption
func (_e *TpmSignerCreator_Expecter) CreateKey(opts ...interface{}) *TpmSignerCreator_CreateKey_Call {
	return &TpmSignerCreator_CreateKey_Call{Call: _e.mock.On("CreateKey",
		append([]interface{}{}, opts...)...)}
}

func (_c *TpmSignerCreator_CreateKey_Call) Run(run func(opts ...tpm.TpmSignerOption)) *TpmSignerCreator_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []tpm.TpmSignerOption
		variadicArgs := make([]tpm.TpmSignerOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(tpm.TpmSignerOption)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *TpmSignerCreator_CreateKey_Call) Return(private []byte, public []byte, err error) *TpmSignerCreator_CreateKey_Call {
	_c.Call.Return(private, public, err)
	return _c
}

func (_c *TpmSignerCreator_CreateKey_Call) RunAndReturn(run func(opts ...tpm.TpmSignerOption) ([]byte, []byte, error)) *TpmSignerCreator_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type TpmSignerCreator
func (_mock *TpmSignerCreator) New(private []byte, public []byte) (crypto.Signer, error) {
	ret := _mock.Called(private, public)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 crypto.Signer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) (crypto.Signer, error)); ok {
		return returnFunc(private, public)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) crypto.Signer); ok {
		r0 = returnFunc(private, public)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.Signer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(private, public)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TpmSignerCreator_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type TpmSignerCreator_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - private []byte
//   - public []byte
func (_e *TpmSignerCreator_Expecter) New(private interface{}, public interface{}) *TpmSignerCreator_New_Call {
	return &TpmSignerCreator_New_Call{Call: _e.mock.On("New", private, public)}
}

func (_c *TpmSignerCreator_New_Call) Run(run func(private []byte, public []byte)) *TpmSignerCreator_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TpmSignerCreator_New_Call) Return(signer crypto.Signer, err error) *TpmSignerCreator_New_Call {
	_c.Call.Return(signer, err)
	return _c
}

func (_c *TpmSignerCreator_New_Call) RunAndReturn(run func(private []byte, public []byte) (crypto.Signer, error)) *TpmSignerCreator_New_Call {
	_c.Call.Return(run)
	return _c
}
