//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.616, BuildCommit: 7ec6dfccdd34fe0928cb63e8e82faeadfed510ae)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
//    - LC_SOURCE_VERSION: 455.20.6.9.20
//
#ifndef FMDFMMAccountInfo_h
#define FMDFMMAccountInfo_h
@import Foundation;

@interface FMDFMMAccountInfo : NSObject <NSSecureCoding>

@property (retain, nonatomic) NSString *dsid;
@property (retain, nonatomic) NSString *username;
@property (retain, nonatomic) NSString *fmmAuthToken;
@property (retain, nonatomic) NSDictionary *additionalInfo;
@property (retain, nonatomic) NSString *fmdServerHost;
@property (retain, nonatomic) NSString *fmdServerProtocolScheme;
@property (retain, nonatomic) NSString *fmdAPSEnvironment;
@property (retain, nonatomic) NSString *fmdIDSIdentifier;
@property (retain, nonatomic) NSString *rootVolumeUUID;
@property (retain, nonatomic) NSString *userGUID;
@property (nonatomic) unsigned int uid;
@property (readonly, nonatomic) _Bool hasMandatoryInfo;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (id)initWithCoder:(id)coder;
- (void)dealloc;

@end

#endif /* FMDFMMAccountInfo_h */
