//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.616, BuildCommit: 7ec6dfccdd34fe0928cb63e8e82faeadfed510ae)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
//    - LC_SOURCE_VERSION: 455.20.6.9.20
//
#ifndef FMNSXPCConnecting_Protocol_h
#define FMNSXPCConnecting_Protocol_h
@import Foundation;

@protocol FMNSXPCConnecting <NSObject>

@required

/* required instance methods */
- (void)invalidate;
- (void)addFailureBlock:(id /* block */)block;
- (id)remoteObjectProxy;

@optional

@end

#endif /* FMNSXPCConnecting_Protocol_h */
